### PR TITLE
fix(share_plus): Add missing call to result for shareUri on iOS

### LINKED ISSUE #2609: [Bug]: Share Plus calling `Share.shareUri` return a never complete future
### Platform

iPhone 15 Pro Max Simulator - iOS 17.2 (21C62) and iPhone Xs Max - 15.6

### Plugin

share_plus

### Version

7.2.2

### Flutter SDK

3.16.7

### Steps to reproduce

Call `Share.shareUri` method

### Code Sample

_No response_

### Logs

```shell
The 'callbacks' channel sent a message from native to Flutter on a non-platform thread. Platform channel messages must be sent on the platform thread. Failure to do so may result in data loss or crashes, and must be fixed in the plugin or application code creating that channel.
```

### Flutter Doctor

```shell
[✓] Flutter (Channel stable, 3.16.7, on macOS 14.2.1 23C71 darwin-arm64, locale en-VN)
    • Flutter version 3.16.7 on channel stable at /Users/lethanh/fvm/versions/3.16.7
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision ef1af02aea (6 weeks ago), 2024-01-11 15:19:26 -0600
    • Engine revision 4a585b7929
    • Dart version 3.2.4
    • DevTools version 2.28.5

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at /Users/lethanh/Library/Android/sdk
    • Platform android-34, build-tools 34.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.7+0-17.0.7b1000.6-10550314)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 15.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 15C500b
    • CocoaPods version 1.13.0

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2023.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • android-studio-dir = /Applications/Android Studio.app
    • Java version OpenJDK Runtime Environment (build 17.0.7+0-17.0.7b1000.6-10550314)

[✓] VS Code (version 1.85.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.80.0

[✓] Connected device (4 available)
    • sdk gphone64 arm64 (mobile) • emulator-5554                        • android-arm64  • Android 13 (API 33) (emulator)
    • iPhone 15 Pro Max (mobile)  • 6C1D369C-B76B-47D6-A7D0-6DF69151F4B4 • ios            • com.apple.CoreSimulator.SimRuntime.iOS-17-2 (simulator)
    • macOS (desktop)             • macos                                • darwin-arm64   • macOS 14.2.1 23C71 darwin-arm64
    • Chrome (web)                • chrome                               • web-javascript • Google Chrome 121.0.6167.184

[✓] Network resources
    • All expected network resources are available.

• No issues found!
```

### Checklist before submitting a bug

- [X] I searched issues in this repository and couldn't find such bug/problem
- [X] I Google'd a solution and I couldn't find it
- [X] I searched on StackOverflow for a solution and I couldn't find it
- [X] I read the README.md file of the plugin
- [X] I'm using the latest version of the plugin
- [X] All dependencies are up to date with `flutter pub upgrade`
- [X] I did a `flutter clean`
- [X] I tried running the example project

### PR DESCRIPTION
**Pull request by miquelbeltran**
## Description

- The code was never completing when being awaited.
- This is due to the missing call to `result(nil)`.
- Tested on iOS simulator using example project.

## Related Issues

- Fix #2609 

## Checklist

- [x] I read the [Contributor Guide](https://github.com/fluttercommunity/plus_plugins/blob/main/CONTRIBUTING.md) and followed the process outlined there for submitting PRs.
- [x] I titled the PR using [Conventional Commits](https://www.conventionalcommits.org/en/v1.0.0).
- [x] I did not modify the `CHANGELOG.md` nor the plugin version in `pubspec.yaml` files.
- [x] All existing and new tests are passing.
- [x] The analyzer (`flutter analyze`) does not report any problems on my PR.

## Breaking Change

Does your PR require plugin users to manually update their apps to accommodate your change?

- [ ] Yes, this is a breaking change (please indicate that with a `!` in the title as explained in [Conventional Commits](https://www.conventionalcommits.org/en/v1.0.0)).
- [x] No, this is *not* a breaking change.

### CODE REVIEW

File: packages/share_plus/share_plus/ios/Classes/FPPSharePlusPlugin.m [hunk 1]
```diff
@@ -358,6 +358,8 @@ + (void)registerWithRegistrar:(NSObject<FlutterPluginRegistrar> *)registrar {
                     atSource:originRect
                     toResult:result
                   withResult:withResult];
+          if (!withResult)
+            result(nil);
```
Comment (miquelbeltran) [inline packages/share_plus/share_plus/ios/Classes/FPPSharePlusPlugin.m:362]: `withResult` may always be false in shareUri, so I am tempted to just always call to `result(nil)`.

However, since this value comes from the Dart side, we cannot warranty that in native code. That's why I added the if-condition here.

**Comment by miquelbeltran** [comment]
Tested on iOS simulator using example project.

**Review by vbuberen — APPROVED** [review]
