### PR TITLE
[battery_plus_info] Fix NPE on modern Samsung devices

### LINKED ISSUE #713: [battery_plus] isInBatterySaveMode fails will NullPointerException
## System info

Using a Samsung S21 (SM-G991W)
Platform the Issue occurs on: android 12 (targetSdkVersion 31)
Plugin name: battery_plus
Plugin version: 2.1.0

## Steps to Reproduce

```dart
      final Battery battery = Battery();
      final isInBatterySaveMode = await battery.isInBatterySaveMode;
```
yields to the following error message
```
PlatformException(error, Attempt to invoke virtual method 'boolean java.lang.String.equals(java.lang.Object)' on a null object reference, null, java.lang.NullPointerException: Attempt to invoke virtual method 'boolean java.lang.String.equals(java.lang.Object)' on a null object reference
I/flutter (22574): 	at dev.fluttercommunity.plus.battery.BatteryPlusPlugin.getPowerSaveModeSamsung(BatteryPlusPlugin.java:167)
...
```

<details>
<summary>Logs</summary>

```dart
[  +15 ms] E/MethodChannel#dev.fluttercommunity.plus/battery(29604): Failed to handle method call
[        ] E/MethodChannel#dev.fluttercommunity.plus/battery(29604): java.lang.NullPointerException: Attempt to invoke virtual method 'boolean java.lang.String.equals(java.lang.Object)' on a null object reference
[        ] E/MethodChannel#dev.fluttercommunity.plus/battery(29604):    at dev.fluttercommunity.plus.battery.BatteryPlusPlugin.getPowerSaveModeSamsung(BatteryPlusPlugin.java:167)
[        ] E/MethodChannel#dev.fluttercommunity.plus/battery(29604):    at dev.fluttercommunity.plus.battery.BatteryPlusPlugin.isInPowerSaveMode(BatteryPlusPlugin.java:154)
[        ] E/MethodChannel#dev.fluttercommunity.plus/battery(29604):    at dev.fluttercommunity.plus.battery.BatteryPlusPlugin.onMethodCall(BatteryPlusPlugin.java:85)
[        ] E/MethodChannel#dev.fluttercommunity.plus/battery(29604):    at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:262)
[        ] E/MethodChannel#dev.fluttercommunity.plus/battery(29604):    at io.flutter.embedding.engine.dart.DartMessenger.invokeHandler(DartMessenger.java:178)
[        ] E/MethodChannel#dev.fluttercommunity.plus/battery(29604):    at io.flutter.embedding.engine.dart.DartMessenger.lambda$handleMessageFromDart$0$DartMessenger(DartMessenger.java:206)
[        ] E/MethodChannel#dev.fluttercommunity.plus/battery(29604):    at io.flutter.embedding.engine.dart.-$$Lambda$DartMessenger$6ZD1MYkhaLxyPjtoFDxe45u43DI.run(Unknown Source:12)
[        ] E/MethodChannel#dev.fluttercommunity.plus/battery(29604):    at android.os.Handler.handleCallback(Handler.java:938)
[        ] E/MethodChannel#dev.fluttercommunity.plus/battery(29604):    at android.os.Handler.dispatchMessage(Handler.java:99)
[        ] E/MethodChannel#dev.fluttercommunity.plus/battery(29604):    at android.os.Looper.loopOnce(Looper.java:226)
[        ] E/MethodChannel#dev.fluttercommunity.plus/battery(29604):    at android.os.Looper.loop(Looper.java:313)
[        ] E/MethodChannel#dev.fluttercommunity.plus/battery(29604):    at android.app.ActivityThread.main(ActivityThread.java:8582)
[        ] E/MethodChannel#dev.fluttercommunity.plus/battery(29604):    at java.lang.reflect.Method.invoke(Native Method)
[        ] E/MethodChannel#dev.fluttercommunity.plus/battery(29604):    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:563)
[        ] E/MethodChannel#dev.fluttercommunity.plus/battery(29604):    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1133)
[   +2 ms] E/flutter (29604): [ERROR:flutter/lib/ui/ui_dart_state.cc(209)] Unhandled Exception: PlatformException(error, Attempt to invoke virtual method 'boolean java.lang.String.equals(java.lang.Object)' on a null object reference, null, java.lang.NullPointerException: Attempt to invoke virtual method 'boolean java.lang.String.equals(java.lang.Object)' on a null object reference
[        ] E/flutter (29604):   at dev.fluttercommunity.plus.battery.BatteryPlusPlugin.getPowerSaveModeSamsung(BatteryPlusPlugin.java:167)
[        ] E/flutter (29604):   at dev.fluttercommunity.plus.battery.BatteryPlusPlugin.isInPowerSaveMode(BatteryPlusPlugin.java:154)
[        ] E/flutter (29604):   at dev.fluttercommunity.plus.battery.BatteryPlusPlugin.onMethodCall(BatteryPlusPlugin.java:85)
[        ] E/flutter (29604):   at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:262)
[        ] E/flutter (29604):   at io.flutter.embedding.engine.dart.DartMessenger.invokeHandler(DartMessenger.java:178)
[        ] E/flutter (29604):   at io.flutter.embedding.engine.dart.DartMessenger.lambda$handleMessageFromDart$0$DartMessenger(DartMessenger.java:206)
[        ] E/flutter (29604):   at io.flutter.embedding.engine.dart.-$$Lambda$DartMessenger$6ZD1MYkhaLxyPjtoFDxe45u43DI.run(Unknown Source:12)
[        ] E/flutter (29604):   at android.os.Handler.handleCallback(Handler.java:938)
[        ] E/flutter (29604):   at android.os.Handler.dispatchMessage(Handler.java:99)
[        ] E/flutter (29604):   at android.os.Looper.loopOnce(Looper.java:226)
[        ] E/flutter (29604):   at android.os.Looper.loop(Looper.java:313)
[        ] E/flutter (29604):   at android.app.ActivityThread.main(ActivityThread.java:8582)
[        ] E/flutter (29604):   at java.lang.reflect.Method.invoke(Native Method)
[        ] E/flutter (29604):   at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:563)
[        ] E/flutter (29604):   at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1133)
[        ] E/flutter (29604): )
[        ] E/flutter (29604): #0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:607:7)
[        ] E/flutter (29604): #1      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:167:18)
[        ] E/flutter (29604): <asynchronous suspension>
[        ] E/flutter (29604): #2      QuestViewModel.checkIfBatterySaveModeOn (package:afkcredits/ui/views/common_viewmodels/quest_viewmodel.dart:158:33)
[        ] E/flutter (29604): <asynchronous suspension>
[        ] E/flutter (29604): #3      QuestViewModel.startQuestMain (package:afkcredits/ui/views/common_viewmodels/quest_viewmodel.dart:122:5)
[        ] E/flutter (29604): <asynchronous suspension>
[        ] E/flutter (29604): #4      ActiveMapQuestViewModel.maybeStartQuest (package:afkcredits/ui/views/active_map_quest/active_map_quest_viewmodel.dart:58:11)
[        ] E/flutter (29604): <asynchronous suspension>
[        ] E/flutter (29604): 
[ +155 ms] I/Counters(29604): exceeded sample count in FrameTime
[+5938 ms] I/Counters(29604): exceeded sample count in FrameTime
[+5094 ms] I/Counters(29604): exceeded sample count in FrameTime
[+2227 ms] I/Counters(29604): exceeded sample count in FrameTime
[+1142 ms] I/Counters(29604): exceeded sample count in FrameTime
[+4601 ms] Application finished.

```

</details>

<details>
<summary>Flutter doctor output</summary>

```
[✓] Flutter (Channel stable, 2.8.1, on macOS 11.5.2 20G95 darwin-x64, locale en-CA)
    • Flutter version 2.8.1 at /usr/local/Cellar/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 77d935af4d (6 weeks ago), 2021-12-16 08:37:33 -0800
    • Engine revision 890a5fca2e
    • Dart version 2.15.1

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /Users/bj/Library/Android/sdk
    • Platform android-31, build-tools 30.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[!] Xcode - develop for iOS and macOS (Xcode 12.5.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    ! Flutter recommends a minimum Xcode version of 13.0.0.
      Download the latest version or update via the Mac App Store.
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 46.0.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.63.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.32.0

[✓] Connected device (2 available)
    • SM G991W (mobile) • R5CR605LX1Y • android-arm64  • Android 12 (API 31)
    • Chrome (web)      • chrome      • web-javascript • Google Chrome 97.0.4692.99

! Doctor found issues in 1 category.
```

</details>

### PR DESCRIPTION
**Pull request by vbuberen**
## Description

This PR addresses the issue for users with Samsung devices with new Android versions where check `isInBatterySaveMode()` was throwing a null pointer exception. It seems that since some time ago (I suspect it happened when Samsung switched from TouchWiz to OneUI) there is no need in using some Samsung specific APIs and values. Due to this change the standard Android API to check batter save mode works fine and returns proper result. 

Since we don't know for sure which Samsung devices use old Samsung way and which not I have just added an additional check to see if calling old API returns null and in such case just call an Android default `PowerManager` to check the mode.

Fix was tested on Galaxy S9+ with Android 10 / One UI 2.5

## Related Issues

Closes #713 

## Checklist

Before you create this PR confirm that it meets all requirements listed below by checking the relevant checkboxes (`[x]`).
This will ensure a smooth and quick review process.

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] My PR includes unit or integration tests for *all* changed/updated/fixed behaviors (See [Contributor Guide]).
- [x] All existing and new tests are passing.
- [x] I updated the version in `pubspec.yaml` and `CHANGELOG.md`.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] The analyzer (`flutter analyze`) does not report any problems on my PR.
- [x] I read and followed the [Flutter Style Guide].
- [x] I am willing to follow-up on review comments in a timely manner.

## Breaking Change

Does your PR require plugin users to manually update their apps to accommodate your change?

- [ ] Yes, this is a breaking change (please indicate a breaking change in CHANGELOG.md and increment major revision).
- [x] No, this is *not* a breaking change.

[issue database]: https://github.com/flutter/flutter/issues
[Contributor Guide]: https://github.com/fluttercommunity/plus_plugins/blob/main/CONTRIBUTING.md
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[pub versioning philosophy]: https://dart.dev/tools/pub/versioning

### CODE REVIEW

File: packages/battery_plus/battery_plus/android/src/main/java/dev/fluttercommunity/plus/battery/BatteryPlusPlugin.java [hunk 1]
```diff
@@ -107,7 +110,7 @@ public void onListen(Object arguments, EventSink events) {
 
   private String getBatteryStatus() {
     int status;
-    if (android.os.Build.VERSION.SDK_INT >= android.os.Build.VERSION_CODES.LOLLIPOP) {
+    if (android.os.Build.VERSION.SDK_INT >= VERSION_CODES.O) {
```
Comment (vbuberen) [inline packages/battery_plus/battery_plus/android/src/main/java/dev/fluttercommunity/plus/battery/BatteryPlusPlugin.java:113]: BATTERY_PROPERTY_STATUS was added just in `O`, so there was an error here. However, this method was called from a method with annotation `TargetAPI(O)`, so this is why we haven't seen users reporting issues with this call.

**Review by miquelbeltran — APPROVED** [review]
Thanks for fixing!
