### PR TITLE
fix(device_info_plus)!: return type of isPhysicalDevice as boolean for ios

### LINKED ISSUE #2483: [Bug]: Why 'isPhysicalDevice' type as String on iOS? It's bool on Android.
### Platform

iOS 16.2

### Plugin

device_info_plus

### Version

9.1.0

### Flutter SDK

3.16.5

### Steps to reproduce

I'm trying to check is user using real device or not.

### Code Sample

```dart
void getDeviceInfo() async {
    await DeviceInfoPlugin().deviceInfo.then((value) {
      print(value.data);
      print(value.data['isPhysicalDevice']);
      print(value.data['isPhysicalDevice'].runtimeType.toString());

      setState(() {
        isPhysicalDevice = value.data['isPhysicalDevice'];
      });
    });
  }
```

### Logs

```shell
flutter: {systemName: iOS, isPhysicalDevice: false, utsname: {release: 21.6.0, sysname: Darwin, nodename: Kimias-MacBook-Air.local, machine: iPhone15,3, version: Darwin Kernel Version 21.6.0: Thu Nov  9 00:38:19 PST 2023; root:xnu-8020.240.18.705.10~1/RELEASE_X86_64}, model: iPhone, localizedModel: iPhone, systemVersion: 16.2, name: iPhone 14 Pro Max, identifierForVendor: 1D01D878-3B63-4B75-8990-5C869043C720}
flutter: false
flutter: String
flutter: type 'String' is not a subtype of type 'bool'
```
```


### Flutter Doctor

```shell
[✓] Flutter (Channel stable, 3.16.5, on macOS 12.7.2 21G1974 darwin-x64, locale en-ID)
    • Flutter version 3.16.5 on channel stable at /Users/me/Development/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 78666c8dc5 (11 days ago), 2023-12-19 16:14:14 -0800
    • Engine revision 3f3e560236
    • Dart version 3.2.3
    • DevTools version 2.28.4

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at /Users/me/Development/Android/sdk
    • Platform android-34, build-tools 34.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.7+0-17.0.7b1000.6-10550314)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14C18
    • CocoaPods version 1.14.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2023.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.7+0-17.0.7b1000.6-10550314)

[✓] VS Code (version 1.85.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.80.0

[✓] Connected device (3 available)
    • iPhone 14 Pro Max (mobile) • 9749841D-1465-4EFC-A035-C22244739XXX • ios            •
      com.apple.CoreSimulator.SimRuntime.iOS-16-2 (simulator)

[✓] Network resources
    • All expected network resources are available.

• No issues found!
```

### Checklist before submitting a bug

- [X] I searched issues in this repository and couldn't find such bug/problem
- [X] I Google'd a solution and I couldn't find it
- [X] I searched on StackOverflow for a solution and I couldn't find it
- [X] I read the README.md file of the plugin
- [X] I'm using the latest version of the plugin
- [X] All dependencies are up to date with `flutter pub upgrade`
- [X] I did a `flutter clean`
- [X] I tried running the example project

### PR DESCRIPTION
**Pull request by muhib349**
## Description

For iOS devices `isPhysicalDevice` was returned as `String` from native platform, now it is returning boolean from native platform.

## Related Issues

*Replace this paragraph with a list of issues related to this PR from the [issue database](https://github.com/fluttercommunity/plus_plugins/issues). Indicate, which of these issues are resolved or fixed by this PR.*

*e.g.*
- *Fix #2483  *
- *Related N/A*

## Checklist

- [x] I read the [Contributor Guide](https://github.com/fluttercommunity/plus_plugins/blob/main/CONTRIBUTING.md) and followed the process outlined there for submitting PRs.
- [x] I titled the PR using [Conventional Commits](https://www.conventionalcommits.org/en/v1.0.0).
- [x] I did not modify the `CHANGELOG.md` nor the plugin version in `pubspec.yaml` files.
- [x] All existing and new tests are passing.
- [x] The analyzer (`flutter analyze`) does not report any problems on my PR.

## Breaking Change

Does your PR require plugin users to manually update their apps to accommodate your change?

- [ ] Yes, this is a breaking change (please indicate that with a `!` in the title as explained in [Conventional Commits](https://www.conventionalcommits.org/en/v1.0.0)).
- [x] No, this is *not* a breaking change.

### CODE REVIEW

File: packages/device_info_plus/device_info_plus/ios/Classes/FPPDeviceInfoPlusPlugin.m [hunk 1]
```diff
@@ -21,8 +21,10 @@ - (void)handleMethodCall:(FlutterMethodCall *)call
     struct utsname un;
     uname(&un);
 
+    NSNumber *isPhysicalNumber =
+        [NSNumber numberWithBool:[self isDevicePhysical]];
```
Comment (miquelbeltran) [inline packages/device_info_plus/device_info_plus/ios/Classes/FPPDeviceInfoPlusPlugin.m:25]: Objective-C is weird :)

**Comment by miquelbeltran** [comment]
Thanks! Change LGTM, but I want to run it before approval, that will take a day or two.

File: packages/device_info_plus/device_info_plus/ios/Classes/FPPDeviceInfoPlusPlugin.m (hunk 1 above)
Comment (muhib349) [reply packages/device_info_plus/device_info_plus/ios/Classes/FPPDeviceInfoPlusPlugin.m:25]: It was my first time writing code in Objective-C, from a Java and Android background. Undoubtedly, it was horrible for me.

**Review by miquelbeltran — APPROVED** [review]

**Comment by miquelbeltran** [comment]
@vbuberen I changed the title to `fix(device_info_plus)!: ...` to mark it as breaking change.

**Comment by muhib349** [comment]
> I could test it now and it works as expected!
> 
> Just curious, why did you need to use `[NSNumber numberWithBool ..]`? Could not be possible to just pass the boolean value in the result map?

I tried to do so, however, Bool is a primitive data type and we couldn't pass any primitive data types to the map object. That's why I used NSNumber to represent boolean.

**Comment by vbuberen** [comment]
> I could test it now and it works as expected!

This change looks good to me as well. @miquelbeltran are you Ok with merging this change?

**Comment by miquelbeltran** [comment]
All good from my side as well @vbuberen
