### PR TITLE
[android_intent_plus] Fix fallback to implicit intent

### LINKED ISSUE #919: [Bug]: android_intent example "fallback to implicit" does not work
### Platform

Android 

### Plugin

android_intent

### Version

-

### Flutter SDK

3.0.2

### Steps to reproduce

1. Run the example
2. Tap on "Test explicit Intents"
3. Tap on the 6th option: "test explicit intent fallback to implicit"

Then nothing happens, and an error appears in the logs.

### Code Sample

```dart
Use the main.dart in the example
```

### Logs

```shell
An Observatory debugger and profiler on AOSP on IA Emulator is available at:
http://127.0.0.1:43467/hr6-DByh9NM=/
D/eglCodecCommon( 7114): setVertexArrayObject: set vao to 0 (0) 1 0
The Flutter DevTools debugger and profiler on AOSP on IA Emulator is available
at: http://127.0.0.1:9101?uri=http://127.0.0.1:43467/hr6-DByh9NM=/
D/EGL_emulation( 7114): eglMakeCurrent: 0xdf485a80: ver 3 1 (tinfo 0xdf483e70)
D/eglCodecCommon( 7114): setVertexArrayObject: set vao to 0 (0) 1 2
I/IntentSender( 7114): Cannot resolve explicit intent
V/IntentSender( 7114): Sending intent Intent { act=android.intent.action.VIEW dat=https://flutter.dev/... pkg=com.android.chrome.implicit.fallback (has extras) }
E/MethodChannel#dev.fluttercommunity.plus/android_intent( 7114): Failed to handle method call
E/MethodChannel#dev.fluttercommunity.plus/android_intent( 7114): android.content.ActivityNotFoundException: No Activity found to handle Intent { act=android.intent.action.VIEW dat=https://flutter.dev/... pkg=com.android.chrome.implicit.fallback (has extras) }
E/MethodChannel#dev.fluttercommunity.plus/android_intent( 7114): 	at android.app.Instrumentation.checkStartActivityResult(Instrumentation.java:2007)
E/MethodChannel#dev.fluttercommunity.plus/android_intent( 7114): 	at android.app.Instrumentation.execStartActivity(Instrumentation.java:1673)
E/MethodChannel#dev.fluttercommunity.plus/android_intent( 7114): 	at android.app.Activity.startActivityForResult(Activity.java:4586)
E/MethodChannel#dev.fluttercommunity.plus/android_intent( 7114): 	at android.app.Activity.startActivityForResult(Activity.java:4544)
E/MethodChannel#dev.fluttercommunity.plus/android_intent( 7114): 	at android.app.Activity.startActivity(Activity.java:4905)
E/MethodChannel#dev.fluttercommunity.plus/android_intent( 7114): 	at android.app.Activity.startActivity(Activity.java:4873)
E/MethodChannel#dev.fluttercommunity.plus/android_intent( 7114): 	at dev.fluttercommunity.plus.androidintent.IntentSender.send(IntentSender.java:55)
E/MethodChannel#dev.fluttercommunity.plus/android_intent( 7114): 	at dev.fluttercommunity.plus.androidintent.MethodCallHandlerImpl.onMethodCall(MethodCallHandlerImpl.java:95)
E/MethodChannel#dev.fluttercommunity.plus/android_intent( 7114): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:262)
E/MethodChannel#dev.fluttercommunity.plus/android_intent( 7114): 	at io.flutter.embedding.engine.dart.DartMessenger.invokeHandler(DartMessenger.java:295)
E/MethodChannel#dev.fluttercommunity.plus/android_intent( 7114): 	at io.flutter.embedding.engine.dart.DartMessenger.lambda$dispatchMessageToQueue$0$DartMessenger(DartMessenger.java:319)
E/MethodChannel#dev.fluttercommunity.plus/android_intent( 7114): 	at io.flutter.embedding.engine.dart.DartMessenger$$ExternalSyntheticLambda0.run(Unknown Source:12)
E/MethodChannel#dev.fluttercommunity.plus/android_intent( 7114): 	at android.os.Handler.handleCallback(Handler.java:873)
E/MethodChannel#dev.fluttercommunity.plus/android_intent( 7114): 	at android.os.Handler.dispatchMessage(Handler.java:99)
E/MethodChannel#dev.fluttercommunity.plus/android_intent( 7114): 	at android.os.Looper.loop(Looper.java:193)
E/MethodChannel#dev.fluttercommunity.plus/android_intent( 7114): 	at android.app.ActivityThread.main(ActivityThread.java:6669)
E/MethodChannel#dev.fluttercommunity.plus/android_intent( 7114): 	at java.lang.reflect.Method.invoke(Native Method)
E/MethodChannel#dev.fluttercommunity.plus/android_intent( 7114): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
E/MethodChannel#dev.fluttercommunity.plus/android_intent( 7114): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
E/flutter ( 7114): [ERROR:flutter/lib/ui/ui_dart_state.cc(198)] Unhandled Exception: PlatformException(error, No Activity found to handle Intent { act=android.intent.action.VIEW dat=https://flutter.dev/... pkg=com.android.chrome.implicit.fallback (has extras) }, null, android.content.ActivityNotFoundException: No Activity found to handle Intent { act=android.intent.action.VIEW dat=https://flutter.dev/... pkg=com.android.chrome.implicit.fallback (has extras) }
E/flutter ( 7114): 	at android.app.Instrumentation.checkStartActivityResult(Instrumentation.java:2007)
E/flutter ( 7114): 	at android.app.Instrumentation.execStartActivity(Instrumentation.java:1673)
E/flutter ( 7114): 	at android.app.Activity.startActivityForResult(Activity.java:4586)
E/flutter ( 7114): 	at android.app.Activity.startActivityForResult(Activity.java:4544)
E/flutter ( 7114): 	at android.app.Activity.startActivity(Activity.java:4905)
E/flutter ( 7114): 	at android.app.Activity.startActivity(Activity.java:4873)
E/flutter ( 7114): 	at dev.fluttercommunity.plus.androidintent.IntentSender.send(IntentSender.java:55)
E/flutter ( 7114): 	at dev.fluttercommunity.plus.androidintent.MethodCallHandlerImpl.onMethodCall(MethodCallHandlerImpl.java:95)
E/flutter ( 7114): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:262)
E/flutter ( 7114): 	at io.flutter.embedding.engine.dart.DartMessenger.invokeHandler(DartMessenger.java:295)
E/flutter ( 7114): 	at io.flutter.embedding.engine.dart.DartMessenger.lambda$dispatchMessageToQueue$0$DartMessenger(DartMessenger.java:319)
E/flutter ( 7114): 	at io.flutter.embedding.engine.dart.DartMessenger$$ExternalSyntheticLambda0.run(Unknown Source:12)
E/flutter ( 7114): 	at android.os.Handler.handleCallback(Handler.java:873)
E/flutter ( 7114): 	at android.os.Handler.dispatchMessage(Handler.java:99)
E/flutter ( 7114): 	at android.os.Looper.loop(Looper.java:193)
E/flutter ( 7114): 	at android.app.ActivityThread.main(ActivityThread.java:6669)
E/flutter ( 7114): 	at java.lang.reflect.Method.invoke(Native Method)
E/flutter ( 7114): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
E/flutter ( 7114): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
E/flutter ( 7114): )
E/flutter ( 7114): #0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:607:7)
E/flutter ( 7114): #1      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:167:18)
E/flutter ( 7114): <asynchronous suspension>
E/flutter ( 7114): #2      AndroidIntent.launch (package:android_intent_plus/android_intent.dart:150:5)
E/flutter ( 7114): <asynchronous suspension>
E/flutter ( 7114): 
```
```


### Flutter Doctor

```shell
[✓] Flutter (Channel stable, 3.0.2, on Ubuntu 22.04 LTS 5.15.0-39-generic,
    locale en_US.UTF-8)
    • Flutter version 3.0.2 at /home/miquel/dev/tools/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision cd41fdd495 (12 days ago), 2022-06-08 09:52:13 -0700
    • Engine revision f15f824b57
    • Dart version 2.17.3
    • DevTools version 2.12.2

[✓] Android toolchain - develop for Android devices (Android SDK version
    30.0.3)
    • Android SDK at /home/miquel/Android/Sdk
    • Platform android-33, build-tools 30.0.3
    • Java binary at:
      /home/miquel/.local/share/JetBrains/Toolbox/apps/AndroidStudio/ch-0/211.
      7628.21.2111.8309675/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7590822)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at google-chrome

[✓] Linux toolchain - develop for Linux desktop
    • Ubuntu clang version 14.0.0-1ubuntu1
    • cmake version 3.22.1
    • ninja version 1.10.1
    • pkg-config version 0.29.2

[✓] Android Studio (version 2021.1)
    • Android Studio at
      /home/miquel/.local/share/JetBrains/Toolbox/apps/AndroidStudio/ch-0/211.
      7628.21.2111.8309675
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7590822)

[✓] IntelliJ IDEA Community Edition (version 2022.1)
    • IntelliJ at
      /home/miquel/.local/share/JetBrains/Toolbox/apps/IDEA-C/ch-0/221.5080.21
      0
    • Flutter plugin version 66.0.4
    • Dart plugin version 221.5480

[✓] IntelliJ IDEA Community Edition (version 2021.3)
    • IntelliJ at
      /home/miquel/.local/share/JetBrains/Toolbox/apps/IDEA-C/ch-0/213.6777.52
    • Flutter plugin version 63.2.4
    • Dart plugin version 213.5744.122

[✓] VS Code (version 1.66.2)
    • VS Code at /usr/share/code
    • Flutter extension version 3.40.0

[✓] VS Code
    • VS Code at /snap/code/current
    • Flutter extension version 3.40.0

[✓] Connected device (3 available)
    • AOSP on IA Emulator (mobile) • emulator-5554 • android-x86    • Android
      9 (API 28) (emulator)
    • Linux (desktop)              • linux         • linux-x64      • Ubuntu
      22.04 LTS 5.15.0-39-generic
    • Chrome (web)                 • chrome        • web-javascript • Google
      Chrome 102.0.5005.115

[✓] HTTP Host Availability
    • All required HTTP hosts are available
```
```

### PR DESCRIPTION
**Pull request by vbuberen**
## Description

Fix for #245 broke the functionality of safe fallback from explicit to implicit intent when package can't be resolved. This PR adds such functionality back.

Additionally updated Android Gradle plugin and used Gradle version.

## Related Issues

Closes #919 

## Checklist

Before you create this PR confirm that it meets all requirements listed below by checking the relevant checkboxes (`[x]`).
This will ensure a smooth and quick review process.

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] My PR includes unit or integration tests for *all* changed/updated/fixed behaviors (See [Contributor Guide]).
- [x] All existing and new tests are passing.
- [x] I updated the version in `pubspec.yaml` and `CHANGELOG.md`.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] The analyzer (`flutter analyze`) does not report any problems on my PR.
- [x] I read and followed the [Flutter Style Guide].
- [x] I am willing to follow-up on review comments in a timely manner.

## Breaking Change

Does your PR require plugin users to manually update their apps to accommodate your change?

- [ ] Yes, this is a breaking change (please indicate a breaking change in CHANGELOG.md and increment major revision).
- [x] No, this is *not* a breaking change.

[issue database]: https://github.com/flutter/flutter/issues
[Contributor Guide]: https://github.com/fluttercommunity/plus_plugins/blob/main/CONTRIBUTING.md
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[pub versioning philosophy]: https://dart.dev/tools/pub/versioning

### CODE REVIEW

File: packages/android_intent_plus/android/src/main/java/dev/fluttercommunity/plus/androidintent/MethodCallHandlerImpl.java [hunk 1]
```diff
@@ -92,11 +92,17 @@ public void onMethodCall(@NonNull MethodCall call, @NonNull Result result) {
             action, flags, category, data, arguments, packageName, componentName, type);
 
     if ("launch".equalsIgnoreCase(call.method)) {
-      sender.send(intent);
 
+      if (intent != null && !sender.canResolveActivity(intent)) {
```
Comment (vbuberen) [inline packages/android_intent_plus/android/src/main/java/dev/fluttercommunity/plus/androidintent/MethodCallHandlerImpl.java:96]: I have just moved this check from `buildIntent()` to be able to set package as `null`, so the system just opens a chooser.

**Review by miquelbeltran — APPROVED** [review]
