### PR TITLE
[share_plus] Fix types, lower Android minSDK

### LINKED ISSUE #758: [share_plus]  Type mismatch: inferred type is String? but String was expected
## System info

Platform the Issue occurs on:  build error 
Plugin name: share plus
Plugin version: 3.1.0
flutter sdk : 2.11.0 - master channel

<details>
<summary>Logs</summary>

```
/share_plus-3.1.0/android/src/main/kotlin/dev/fluttercommunity/plus/share/MethodCallHandler.kt: (34, 24): Type mismatch: inferred type is String? but String was expected
```

</details>

<details>
<summary>Flutter doctor output</summary>

```
[✓] Flutter (Channel master, 2.11.0-0.0.pre.633, on macOS 12.2.1 21D62
    darwin-arm, locale ko-KR)
[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 13.2.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2020.3)
[✓] IntelliJ IDEA Community Edition (version 2021.3.2)
[✓] VS Code (version 1.64.2)
[✓] Connected device (3 available)
[✓] HTTP Host Availability
```

</details>

### LINKED ISSUE #789: share_plus Android minSdk bump drops support for a lot of devices
## System info

Platform the Issue occurs on: Android
Plugin name: share_plus
Plugin version: 4.0.1

## Steps to Reproduce

The latest `share_pus` plugin update bumped minSdk Android API from 16 to 23 (from Android 4.1 to Android 6). With Flutter itself supporting API 16 that is a large drop of supported Android devices.

My app is primarily used on Android tablets, and there is a lot of them running older Android versions. For example, older generation Amazon Fire 7 tablets (Fire OS 5 is API level 22) and some of 3..4 year old Samsung's Tab As are also running Android 5 or older.

### PR DESCRIPTION
**Pull request by vbuberen**
## Description

In this PR I fixed issues with type in `result.error()`, which some users reported in #758. Saw that the code wasn't formatted according to our `editorconfig` file, which was added some time ago, so reformatted the code.

I didn't like that `share_plus` now has minSDK 23 as it cuts quite a lot of users/devices. I thought we could make it much lower, but it seems that 22 is the minimum possible, because `Intent.createChooser()` with `sender` parameter appeared only in SDK 22. So I made required changes to set minSDK to 22 and some additional small fixes.

Finally, I saw that in #788 there were changes to min Flutter version, but not all platforms were updated. Fixed it as well, so `share_plus` requires Flutter 1.20 on all platforms now.

## Related Issues

Closes #758
Partially closes #789 

## Checklist

Before you create this PR confirm that it meets all requirements listed below by checking the relevant checkboxes (`[x]`).
This will ensure a smooth and quick review process.

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] My PR includes unit or integration tests for *all* changed/updated/fixed behaviors (See [Contributor Guide]).
- [x] All existing and new tests are passing.
- [x] I updated the version in `pubspec.yaml` and `CHANGELOG.md`.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] The analyzer (`flutter analyze`) does not report any problems on my PR.
- [x] I read and followed the [Flutter Style Guide].
- [x] I am willing to follow-up on review comments in a timely manner.

## Breaking Change

Does your PR require plugin users to manually update their apps to accommodate your change?

- [ ] Yes, this is a breaking change (please indicate a breaking change in CHANGELOG.md and increment major revision).
- [x] No, this is *not* a breaking change.

[issue database]: https://github.com/flutter/flutter/issues
[Contributor Guide]: https://github.com/fluttercommunity/plus_plugins/blob/main/CONTRIBUTING.md
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[pub versioning philosophy]: https://dart.dev/tools/pub/versioning

### CODE REVIEW

File: packages/share_plus/share_plus/android/src/main/kotlin/dev/fluttercommunity/plus/share/MethodCallHandler.kt [hunk 1]
```diff
@@ -5,71 +5,74 @@ import io.flutter.plugin.common.MethodChannel
...
+                    share.shareFiles(
+                        call.argument<List<String>>("paths")!!,
+                        call.argument<List<String>?>("mimeTypes"),
+                        call.argument<String?>("text"),
+                        call.argument<String?>("subject"),
+                        false,
+                    )
+                    result.success(null)
+                } catch (e: IOException) {
+                    result.error("Share failed", e.message, null)
```
Comment (Mosc) [inline packages/share_plus/share_plus/android/src/main/kotlin/dev/fluttercommunity/plus/share/MethodCallHandler.kt:39]: I was considering submitting a similar fix, but keep in mind that this may be a breaking change for some users that rely on the returned error code or error message. At the very least it should coincide with more than a simple PATCH version bump.

File: packages/share_plus/share_plus/android/src/main/kotlin/dev/fluttercommunity/plus/share/ShareSuccessManager.kt [hunk 2]
```diff
@@ -36,13 +33,17 @@ internal class ShareSuccessManager(private val context: Context): BroadcastRecei
      * the componentname of the chosen option or an empty string on dismissal.
      */
     fun setCallback(callback: MethodChannel.Result): Boolean {
-        if (calledBack.compareAndSet(true, false)) {
+        return if (calledBack.compareAndSet(true, false)) {
```
Comment (Coronon) [inline packages/share_plus/share_plus/android/src/main/kotlin/dev/fluttercommunity/plus/share/ShareSuccessManager.kt:36]: While this does do the job, don't you agree that this makes the code less readable? We don't really get anything from this change, and it's not consistent (see lines 72-77).

**Comment by Mosc** [comment]
Not sure how these cases are generally handled, but I would prefer the `minSdkVersion` to go all the way back to 16 and simply return an appropriate `result.error(...)` for `shareWithResult` and `shareFilesWithResult` on SDK versions lower than 22. That would allow users to just continue to use `share` and `shareFiles` as they did before v4.0.0.

**Comment by Coronon** [comment]
> Not sure how these cases are generally handled, but I would prefer the `minSdkVersion` to go all the way back to 16 and simply return an appropriate `result.error(...)` for `shareWithResult` and `shareFilesWithResult` on SDK versions lower than 22. That would allow users to just continue to use `share` and `shareFiles` as they did before v4.0.0.

As said - I am pretty new to Android development. If that compiles and works as expected, it is probably the best option we have. The only risk I see there is people unintentionally using `shareWithResult` with a `minSdkVersion` lower than 16 and not noticing because their development environment is API level 22+. This could lead to users effected by unforeseen errors - can we somehow statically check this at compile time?

File: packages/share_plus/share_plus/android/src/main/kotlin/dev/fluttercommunity/plus/share/ShareSuccessManager.kt (hunk 2 above)
Comment (vbuberen) [reply packages/share_plus/share_plus/android/src/main/kotlin/dev/fluttercommunity/plus/share/ShareSuccessManager.kt:36]: No, I don't think so. It is a normal Kotlin syntax, which is used for a long time in Android development. If you would use Android Studio you would even see a lint suggestion to change this way. 
Lines you suggested to consider are a different case, which can't be turned into construction like here.

File: packages/share_plus/share_plus/android/src/main/kotlin/dev/fluttercommunity/plus/share/MethodCallHandler.kt (hunk 1 above)
Comment (vbuberen) [reply packages/share_plus/share_plus/android/src/main/kotlin/dev/fluttercommunity/plus/share/MethodCallHandler.kt:39]: I doubt that somebody relied on this as otherwise this person would open an issue that `e.message` was set on a place of `errorCode` parameter.

File: packages/share_plus/share_plus/android/src/main/kotlin/dev/fluttercommunity/plus/share/ShareSuccessManager.kt (hunk 2 above)
Comment (Coronon) [reply packages/share_plus/share_plus/android/src/main/kotlin/dev/fluttercommunity/plus/share/ShareSuccessManager.kt:36]: Well, you could just do this on lines 72-77:
```kotlin
return if (requestCode == ACTIVITY_CODE) {
    returnResult("")
    true
} else {
    false
}
```

File: packages/share_plus/share_plus/android/src/main/kotlin/dev/fluttercommunity/plus/share/MethodCallHandler.kt (hunk 1 above)
Comment (Mosc) [reply packages/share_plus/share_plus/android/src/main/kotlin/dev/fluttercommunity/plus/share/MethodCallHandler.kt:39]: Right, I would also doubt it, but no reason not to err on the side of caution in terms of versioning.

**Comment by Mosc** [comment]
> > Not sure how these cases are generally handled, but I would prefer the `minSdkVersion` to go all the way back to 16 and simply return an appropriate `result.error(...)` for `shareWithResult` and `shareFilesWithResult` on SDK versions lower than 22. That would allow users to just continue to use `share` and `shareFiles` as they did before v4.0.0.
> 
> As said - I am pretty new to Android development. If that compiles and works as expected, it is probably the best option we have. The only risk I see there is people unintentionally using `shareWithResult` with a `minSdkVersion` lower than 16 and not noticing because their development environment is API level 22+. This could lead to users effected by unforeseen errors - can we somehow statically check this at compile time? And API version 22 is from 2015, so is this really necessary?

I understand your concerns. A runtime error is certainly not ideal, although to be fair, `shareWithResult` and `shareFilesWithResult` _already_ fail on runtime on web, Windows and Linux despite the package claiming those platforms are supported! We rely on the user reading the documentation for those specific methods.

How about falling back to the regular non-result based share operations and just returning `ShareResultStatus.unavailable` for Android SDKs under 22?

File: packages/share_plus/share_plus/android/src/main/kotlin/dev/fluttercommunity/plus/share/ShareSuccessManager.kt (hunk 2 above)
Comment (vbuberen) [reply packages/share_plus/share_plus/android/src/main/kotlin/dev/fluttercommunity/plus/share/ShareSuccessManager.kt:36]: > Well, you could just do this on lines 72-77 or am I wrong?

You are right, I overlooked that case.

> guess I just don't like how it looks 🤷🏻‍♂️

Just a case of tastes, I guess, because for me as for the person, who was working with Kotlin for a long time it seems fine. Will update code for consistency, though.

**Comment by vbuberen** [comment]
> How about falling back to the regular non-result based share operations and just returning `ShareResultStatus.unavailable` for Android SDKs under 22?

I agree that we should rework the solution with sharing with result. Not sure I can jump right into it (because an Android dev for quite some time and might be the right person to take care of it) as I am quite occupied with some activities here in Ukraine due to infamous events, so don't have much time. But let's see how it goes.

File: packages/share_plus/share_plus/android/src/main/kotlin/dev/fluttercommunity/plus/share/MethodCallHandler.kt [hunk 3]
```diff
@@ -5,71 +5,74 @@ import io.flutter.plugin.common.MethodChannel
...
+                }
+            }
+            "shareWithResult" -> {
+                expectMapArguments(call)
```
Comment (ekuleshov) [inline packages/share_plus/share_plus/android/src/main/kotlin/dev/fluttercommunity/plus/share/MethodCallHandler.kt:43]: could these `*withResults(..)` methods extended with check like

```
if(Build.VERSION.SDK_INT > Build.VERSION_CODES.LOLLIPOP_MR1)
  result.notImplemented()
else ...
```

Then it won't be necessary to bump the `minSdkVersion` version for Android platform and it could be kept at the level supported in `3.x` version of plugin.

**Comment by Coronon** [comment]
> How about falling back to the regular non-result based share operations and just returning `ShareResultStatus.unavailable` for Android SDKs under 22?

That sounds like a good idea, as we already have that status and would not need to break any existing APIs as of version 4.0.1

I might even try to implement that tomorrow

**Comment by ekuleshov** [comment]
> How about falling back to the regular non-result based share operations and just returning `ShareResultStatus.unavailable` for Android SDKs under 22?

Thank you for looking into this.

Now, if some platform would return `ShareResultStatus.unavailable`, perhaps it would be more consistent to do the same on web, linux and windows too instead of tossing not supported runtime exception on those?

**Comment by Coronon** [comment]
I will fork this fork to base my PR on the better formatted code

**Comment by vbuberen** [comment]
> I will fork this fork to base my PR on the better formatted code

I wouldn't bother yourself with that to depend on this PR, since I don't know for sure as to when it gets a review.

If it is just about formatting - auto formatting should work fine for you no matter which IDE you use as the project has an editorconfig file in its root, so code format should be forced according to riles in that file.

**Comment by Coronon** [comment]
> If it is just about formatting - auto formatting should work fine for you no matter which IDE you use as the project has an editorconfig file in its root, so code format should be forced according to riles in that file.

I only use melos format, which seems to not yield the same result as your formatting, but ok, will depend on the main branch then

**Comment by Coronon** [comment]
Just pushed my changes, please try this example project with your low API version devices/emulators: https://github.com/Coronon/share_plus_result_example

**Review by miquelbeltran — APPROVED** [review]
Thank you @vbuberen !

File: packages/share_plus/share_plus/android/src/main/kotlin/dev/fluttercommunity/plus/share/MethodCallHandler.kt (hunk 3 above)
Comment (miquelbeltran) [reply packages/share_plus/share_plus/android/src/main/kotlin/dev/fluttercommunity/plus/share/MethodCallHandler.kt:43]: I think so. If anyone can submit a separated PR with a that change, that would be awesome!

**Comment by miquelbeltran** [comment]
and published
