### PR TITLE
fix(share_plus): return correct share result on android

### LINKED ISSUE #916: [Bug]: SharewithResult always returning null in Android
### Platform

Android 11

### Plugin

share_plus

### Version

4.0.8

### Flutter SDK

3.0.2

### Steps to reproduce

1. use shareFilesWithResult and check the result. result.raw returns null 

### Code Sample

_No response_

### Logs

```shell
[+54664 ms] Observatory URL on device: http://127.0.0.1:34899/7ETFkDQwO_Q=/
[   +2 ms] executing: /Users/vgts/Library/Android/sdk/platform-tools/adb -s emulator-5554 forward tcp:0 tcp:34899
[  +34 ms] 52673
[        ] Forwarded host port 52673 to device port 34899 for Observatory
[  +11 ms] Caching compiled dill
[ +295 ms] Connecting to service protocol: http://127.0.0.1:52673/7ETFkDQwO_Q=/
[ +659 ms] Launching a Dart Developer Service (DDS) instance at http://127.0.0.1:0, connecting to VM service at
http://127.0.0.1:52673/7ETFkDQwO_Q=/.
[ +288 ms] DDS is listening at http://127.0.0.1:52682/LB1yIN6BQhk=/.
[ +103 ms] Successfully connected to service protocol: http://127.0.0.1:52673/7ETFkDQwO_Q=/
[ +173 ms] DevFS: Creating new filesystem on the device (null)
[  +75 ms] DevFS: Created new filesystem on the device (file:///data/user/0/io.flutter.plugins.shareexample/code_cache/exampleWMUXHN/example/)
[   +4 ms] Updating assets
[ +214 ms] Syncing files to device sdk gphone x86...
[   +3 ms] <- reset
[        ] Compiling dart to kernel with 0 updated files
[        ] Processing bundle.
[   +1 ms] <- recompile package:share_example/main.dart 260be2e5-1266-4797-b78b-e46ac513b004
[        ] <- 260be2e5-1266-4797-b78b-e46ac513b004
[   +3 ms] Bundle processing done.
[ +513 ms] Updating files.
[        ] DevFS: Sync finished
[   +2 ms] Syncing files to device sdk gphone x86... (completed in 523ms)
[        ] Synced 0.0MB.
[   +4 ms] <- accept
[   +5 ms] Connected to _flutterView/0xf52865e0.
[   +5 ms] Flutter run key commands.
[   +2 ms] r Hot reload. 🔥🔥🔥
[   +1 ms] R Hot restart.
[        ] h List all available interactive commands.
[        ] d Detach (terminate "flutter run" but leave application running).
[        ] c Clear the screen
[        ] q Quit (terminate the application on the device).
[        ] 💪 Running with sound null safety 💪
[   +1 ms] An Observatory debugger and profiler on sdk gphone x86 is available at: http://127.0.0.1:52682/LB1yIN6BQhk=/
[+2073 ms] The Flutter DevTools debugger and profiler on sdk gphone x86 is available at:
http://127.0.0.1:9100?uri=http://127.0.0.1:52682/LB1yIN6BQhk=/
[+3299 ms] I/AssistStructure(26783): Flattened final assist data: 532 bytes, containing 1 windows, 3 views
[+4850 ms] I/TextInputPlugin(26783): Composing region changed by the framework. Restarting the input method.
[  +13 ms] W/IInputConnectionWrapper(26783): getTextBeforeCursor on inactive InputConnection
[   +6 ms] W/IInputConnectionWrapper(26783): getSelectedText on inactive InputConnection
[   +3 ms] W/IInputConnectionWrapper(26783): getTextAfterCursor on inactive InputConnection
[   +6 ms] W/IInputConnectionWrapper(26783): getTextBeforeCursor on inactive InputConnection
[   +2 ms] W/IInputConnectionWrapper(26783): getSelectedText on inactive InputConnection
[   +3 ms] W/IInputConnectionWrapper(26783): getTextAfterCursor on inactive InputConnection
[  +30 ms] W/IInputConnectionWrapper(26783): beginBatchEdit on inactive InputConnection
[   +4 ms] W/IInputConnectionWrapper(26783): getTextBeforeCursor on inactive InputConnection
[        ] W/IInputConnectionWrapper(26783): endBatchEdit on inactive InputConnection
[   +5 ms] W/IInputConnectionWrapper(26783): beginBatchEdit on inactive InputConnection
[   +2 ms] W/IInputConnectionWrapper(26783): getTextBeforeCursor on inactive InputConnection
[   +1 ms] W/IInputConnectionWrapper(26783): endBatchEdit on inactive InputConnection
[ +113 ms] I/TextInputPlugin(26783): Composing region changed by the framework. Restarting the input method.
[        ] W/IInputConnectionWrapper(26783): getTextBeforeCursor on inactive InputConnection
[   +2 ms] W/IInputConnectionWrapper(26783): getSelectedText on inactive InputConnection
[   +7 ms] W/IInputConnectionWrapper(26783): getTextAfterCursor on inactive InputConnection
[  +24 ms] W/IInputConnectionWrapper(26783): getTextBeforeCursor on inactive InputConnection
[        ] W/IInputConnectionWrapper(26783): getSelectedText on inactive InputConnection
[        ] W/IInputConnectionWrapper(26783): getTextAfterCursor on inactive InputConnection
[  +34 ms] W/IInputConnectionWrapper(26783): beginBatchEdit on inactive InputConnection
[        ] W/IInputConnectionWrapper(26783): getTextBeforeCursor on inactive InputConnection
[        ] W/IInputConnectionWrapper(26783): endBatchEdit on inactive InputConnection
[ +210 ms] I/TextInputPlugin(26783): Composing region changed by the framework. Restarting the input method.
[   +3 ms] W/IInputConnectionWrapper(26783): getTextBeforeCursor on inactive InputConnection
[   +3 ms] W/IInputConnectionWrapper(26783): getSelectedText on inactive InputConnection
[  +13 ms] W/IInputConnectionWrapper(26783): getTextAfterCursor on inactive InputConnection
[   +1 ms] W/IInputConnectionWrapper(26783): getTextBeforeCursor on inactive InputConnection
[        ] W/IInputConnectionWrapper(26783): getSelectedText on inactive InputConnection
[        ] W/IInputConnectionWrapper(26783): getTextAfterCursor on inactive InputConnection
[  +51 ms] W/IInputConnectionWrapper(26783): beginBatchEdit on inactive InputConnection
[        ] W/IInputConnectionWrapper(26783): getTextBeforeCursor on inactive InputConnection
[   +2 ms] W/IInputConnectionWrapper(26783): endBatchEdit on inactive InputConnection
[   +7 ms] W/IInputConnectionWrapper(26783): beginBatchEdit on inactive InputConnection
[        ] W/IInputConnectionWrapper(26783): getTextBeforeCursor on inactive InputConnection
[  +19 ms] W/IInputConnectionWrapper(26783): endBatchEdit on inactive InputConnection
[  +81 ms] I/TextInputPlugin(26783): Composing region changed by the framework. Restarting the input method.
[   +2 ms] W/IInputConnectionWrapper(26783): getTextBeforeCursor on inactive InputConnection
[   +3 ms] W/IInputConnectionWrapper(26783): getSelectedText on inactive InputConnection
[   +9 ms] W/IInputConnectionWrapper(26783): getTextAfterCursor on inactive InputConnection
[+1078 ms] W/IInputConnectionWrapper(26783): getTextBeforeCursor on inactive InputConnection
[   +7 ms] I/AssistStructure(26783): Flattened final assist data: 524 bytes, containing 1 windows, 3 views
[        ] W/IInputConnectionWrapper(26783): getSelectedText on inactive InputConnection
[        ] W/IInputConnectionWrapper(26783): getTextAfterCursor on inactive InputConnection
[ +723 ms] I/TextInputPlugin(26783): Composing region changed by the framework. Restarting the input method.
[   +8 ms] W/IInputConnectionWrapper(26783): getTextBeforeCursor on inactive InputConnection
[   +2 ms] W/IInputConnectionWrapper(26783): getSelectedText on inactive InputConnection
[   +3 ms] W/IInputConnectionWrapper(26783): getTextAfterCursor on inactive InputConnection
[   +3 ms] W/IInputConnectionWrapper(26783): beginBatchEdit on inactive InputConnection
[        ] W/IInputConnectionWrapper(26783): getTextBeforeCursor on inactive InputConnection
[   +9 ms] W/IInputConnectionWrapper(26783): endBatchEdit on inactive InputConnection
[ +173 ms] I/TextInputPlugin(26783): Composing region changed by the framework. Restarting the input method.
[  +12 ms] W/IInputConnectionWrapper(26783): getTextAfterCursor on inactive InputConnection
[   +3 ms] W/IInputConnectionWrapper(26783): beginBatchEdit on inactive InputConnection
[        ] W/IInputConnectionWrapper(26783): endBatchEdit on inactive InputConnection
[  +12 ms] W/IInputConnectionWrapper(26783): setComposingRegion on inactive InputConnection
[        ] W/IInputConnectionWrapper(26783): getTextBeforeCursor on inactive InputConnection
[        ] W/IInputConnectionWrapper(26783): getSelectedText on inactive InputConnection
[        ] W/IInputConnectionWrapper(26783): getTextAfterCursor on inactive InputConnection
[ +313 ms] I/TextInputPlugin(26783): Composing region changed by the framework. Restarting the input method.
[   +6 ms] W/IInputConnectionWrapper(26783): getSelectedText on inactive InputConnection
[   +6 ms] W/IInputConnectionWrapper(26783): getTextAfterCursor on inactive InputConnection
[  +11 ms] W/IInputConnectionWrapper(26783): getTextBeforeCursor on inactive InputConnection
[   +4 ms] W/IInputConnectionWrapper(26783): getSelectedText on inactive InputConnection
[  +14 ms] W/IInputConnectionWrapper(26783): getTextAfterCursor on inactive InputConnection
[  +31 ms] W/IInputConnectionWrapper(26783): beginBatchEdit on inactive InputConnection
[   +2 ms] W/IInputConnectionWrapper(26783): getTextBeforeCursor on inactive InputConnection
[   +2 ms] W/IInputConnectionWrapper(26783): endBatchEdit on inactive InputConnection
[+1244 ms] I/TextInputPlugin(26783): Composing region changed by the framework. Restarting the input method.
[  +49 ms] W/IInputConnectionWrapper(26783): getTextBeforeCursor on inactive InputConnection
[  +13 ms] W/IInputConnectionWrapper(26783): getSelectedText on inactive InputConnection
[  +15 ms] W/IInputConnectionWrapper(26783): getTextAfterCursor on inactive InputConnection
[ +195 ms] W/IInputConnectionWrapper(26783): beginBatchEdit on inactive InputConnection
[        ] W/IInputConnectionWrapper(26783): getTextBeforeCursor on inactive InputConnection
[  +13 ms] W/IInputConnectionWrapper(26783): endBatchEdit on inactive InputConnection
[+1079 ms] I/TextInputPlugin(26783): Composing region changed by the framework. Restarting the input method.
[  +13 ms] W/ListenableEditingState(26783): a listener was added to EditingState while a batch edit was in progress
[  +89 ms] W/IInputConnectionWrapper(26783): endBatchEdit on inactive InputConnection
[  +76 ms] W/IInputConnectionWrapper(26783): setComposingRegion on inactive InputConnection
[        ] W/IInputConnectionWrapper(26783): getTextBeforeCursor on inactive InputConnection
[   +3 ms] W/IInputConnectionWrapper(26783): getSelectedText on inactive InputConnection
[  +20 ms] W/IInputConnectionWrapper(26783): getTextAfterCursor on inactive InputConnection
[  +88 ms] W/IInputConnectionWrapper(26783): getTextBeforeCursor on inactive InputConnection
[        ] W/IInputConnectionWrapper(26783): getSelectedText on inactive InputConnection
[        ] W/IInputConnectionWrapper(26783): getTextAfterCursor on inactive InputConnection
[  +90 ms] W/IInputConnectionWrapper(26783): beginBatchEdit on inactive InputConnection
[        ] W/IInputConnectionWrapper(26783): getTextBeforeCursor on inactive InputConnection
[  +19 ms] W/IInputConnectionWrapper(26783): endBatchEdit on inactive InputConnection
[+8172 ms] I/System.out(26783): onReceuve
[   +2 ms] I/System.out(26783): null
[ +254 ms] I/flutter (26783): ShareResultStatus.success
[        ] I/flutter (26783): null
```

### Flutter Doctor

```shell
[✓] Flutter (Channel stable, 3.0.2, on macOS 12.2.1 21D62 darwin-x64, locale en-IN)
    • Flutter version 3.0.2 at /Users/vgts/Documents/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision cd41fdd495 (11 days ago), 2022-06-08 09:52:13 -0700
    • Engine revision f15f824b57
    • Dart version 2.17.3
    • DevTools version 2.12.2

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Users/vgts/Library/Android/sdk
    • Platform android-31, build-tools 30.0.3
    • ANDROID_HOME = /Users/vgts/Library/Android/sdk
    • ANDROID_SDK_ROOT = /Users/vgts/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7590822)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7590822)

[✓] VS Code (version 1.68.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.42.0

[✓] Connected device (3 available)
    • sdk gphone x86 (mobile) • emulator-5554 • android-x86    • Android 11 (API 30) (emulator)
    • macOS (desktop)         • macos         • darwin-x64     • macOS 12.2.1 21D62 darwin-x64
    • Chrome (web)            • chrome        • web-javascript • Google Chrome 102.0.5005.115

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```

### PR DESCRIPTION
**Pull request by Coronon**
## Description

The `share_plus` android `shareWithResult` and `shareFilesWithResult` implementations are broken. The returned `ShareResult.raw` is always `null` on successful share. This PR fixes this by using `FLAG_MUTABLE` instead of `FLAG_IMMUTABLE`, as pointed out by @aakash-pamnani. This issue was not found when initially implementing the `shareWithResult` methods, as the `FLAG_IMMUTABLE` was only required by the highest API versions. Back then, a simple warning was emitted that strongly suggested using `FLAG_IMMUTABLE`, which seemed to break nothing.

This PR now fixes the behavior and ensures that the `FLAG_MUTABLE` `PendingIntent` given out may not be abused by moving from an implicit internal `Intent` to an explicit one. This also reduces mental complexity of the implementation.

I also added some more documentation throughout the android implementation.

As always, I provide [share_plus_example](https://github.com/Coronon/share_plus_example/tree/31ce889c3eae9e1e3de4264870fe3b11f4b829c8) as a pre-setup example project for this PR.

## Related Issues

Fixes #916

## Checklist

- [x] I read the Contributor Guide and followed the process outlined there for submitting PRs.
- [x] I titled the PR using [Conventional Commits](https://www.conventionalcommits.org/en/v1.0.0).
- [x] I did not modify the `CHANGELOG.md` nor the `pubspec.yaml` files.
- [x] All existing and new tests are passing.
- [x] The analyzer (`flutter analyze`) does not report any problems on my PR.

## Breaking Change

Does your PR require plugin users to manually update their apps to accommodate your change?

- [ ] Yes, this is a breaking change (please indicate that with a `!` in the title as explained in [Conventional Commits](https://www.conventionalcommits.org/en/v1.0.0)).
- [x] No, this is *not* a breaking change.

### CODE REVIEW

**Comment by Coronon** [comment]
The Linux test failed because it got a 404 while installing packages through apt - that should not affect this PR

File: packages/share_plus/share_plus/android/src/main/kotlin/dev/fluttercommunity/plus/share/Share.kt [hunk 1]
```diff
@@ -71,9 +71,9 @@ internal class Share(
                 PendingIntent.getBroadcast(
                     context,
                     0,
-                    Intent(ShareSuccessManager.BROADCAST_CHANNEL),
+                    Intent(context, SharePlusPendingIntent::class.java),
                     PendingIntent.FLAG_UPDATE_CURRENT or immutabilityIntentFlags
-                ).intentSender
+                ).getIntentSender()
```
Comment (vbuberen) [inline packages/share_plus/share_plus/android/src/main/kotlin/dev/fluttercommunity/plus/share/Share.kt:76]: Let's stick with Kotlin getter access syntax as it was before.

File: packages/share_plus/share_plus/android/src/main/kotlin/dev/fluttercommunity/plus/share/SharePlusPendingIntent.kt [hunk 2]
```diff
@@ -0,0 +1,43 @@
...
+ * mutable Intent may carry.
+ *
+ * When the PendingIntent is sent, the system will instantiate this class and call `onReceive` on it.
+ */
+internal class SharePlusPendingIntent: BroadcastReceiver() {
+    /**
+     * Companion object to achieve static behaviour.
+     */
+    companion object {
+        @JvmField
```
Comment (vbuberen) [inline packages/share_plus/share_plus/android/src/main/kotlin/dev/fluttercommunity/plus/share/SharePlusPendingIntent.kt:18]: It is not needed as this var isn't used from Java code.

**Review by vbuberen — COMMENTED** [review]
Tested and it seems to be working good. 

Left a few Kotlin related comments, but otherwise looks good to me.

File: packages/share_plus/share_plus/android/src/main/kotlin/dev/fluttercommunity/plus/share/SharePlusPendingIntent.kt [hunk 3]
```diff
@@ -0,0 +1,43 @@
...
+/**
+ * This helper class allows us to use FLAG_MUTABLE on the PendingIntent used in the Share class,
+ * as it allows us to make the underlying Intent explicit, therefore avoiding any risks an implicit
+ * mutable Intent may carry.
+ *
+ * When the PendingIntent is sent, the system will instantiate this class and call `onReceive` on it.
+ */
+internal class SharePlusPendingIntent: BroadcastReceiver() {
+    /**
+     * Companion object to achieve static behaviour.
```
Comment (vbuberen) [inline packages/share_plus/share_plus/android/src/main/kotlin/dev/fluttercommunity/plus/share/SharePlusPendingIntent.kt:15]: I think this comment is an overkill and doesn't bring value, considering the comment above the var below.

File: packages/share_plus/share_plus/android/src/main/kotlin/dev/fluttercommunity/plus/share/Share.kt (hunk 1 above)
Comment (Coronon) [reply packages/share_plus/share_plus/android/src/main/kotlin/dev/fluttercommunity/plus/share/Share.kt:76]: Actually didn't know that this was a feature of Kotlin - thank you :)

File: packages/share_plus/share_plus/android/src/main/kotlin/dev/fluttercommunity/plus/share/SharePlusPendingIntent.kt (hunk 2 above)
Comment (Coronon) [reply packages/share_plus/share_plus/android/src/main/kotlin/dev/fluttercommunity/plus/share/SharePlusPendingIntent.kt:18]: Actually thought that it would be required for static behavior as I read it everywhere when I googled 'Kotlin static variables' - good to know :)

**Comment by Coronon** [comment]
Thanks for your review! Fixed all points mentioned and updated my example project and all references to it :)

**Comment by miquelbeltran** [comment]
LGTM, but I'll have to run this on Monday before merging.

**Comment by vbuberen** [comment]
> LGTM, but I'll have to run this on Monday before merging.

I have tested it on Android 10 physical device and emulator of Android 12. Worked well.

**Review by vbuberen — APPROVED** [review]
