### PR TITLE
fix(sensors_plus): crashes on devices that don't have the corresponding sensor

### LINKED ISSUE #1404: [Bug]: Exception on specific SM A105F Samsung model
### Platform

Android

### Plugin

Sensor_plus

### Version

2.0.1

### Flutter SDK

3.3.9

### Steps to reproduce

1. I use it to read ```MagnetometerEvent``` but there's an exception on my specific device and the library can't catch it

### Code Sample

```dart
void _listen() {
    _streamSubscriptions.add(
      magnetometerEvents.listen(
        (MagnetometerEvent event) {
          final compassAngle = _getCompassAngle(
            event.x,
            event.y,
          );
          final compassAngleString = _getCompassAngleString(compassAngle);
          emit(QiblaCompassListenSuccess(
            compassAngle,
            '${(((2 * pi) - compassAngle) * kToDegree).round().toString()}° $compassAngleString',
          ));
        },
        onError: (e) {
          emit(const QiblaCompassListenFailure(
            0.0,
            '0° N',
          ));
        },
        cancelOnError: true,
      ),
    );
  }
```

### Logs

```shell
[ +339 ms] 
                    ══╡ EXCEPTION CAUGHT BY SERVICES LIBRARY ╞══════════════════════════════════════════════════════════
                    The following PlatformException was thrown while activating platform stream on channel
                    dev.fluttercommunity.plus/sensors/magnetometer:
                    PlatformException(error, <get-sensor>(...) must not be null, null, null)

                    When the exception was thrown, this was the stack:
                    #0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:653:7)
                    #1      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:296:18)
                    <asynchronous suspension>
                    #2      EventChannel.receiveBroadcastStream.<anonymous closure> (package:flutter/src/services/platform_channel.dart:637:9)
                    <asynchronous suspension>
                    ════════════════════════════════════════════════════════════════════════════════════════════════════
```

### Flutter Doctor

```shell
[√] Flutter (Channel stable, 3.3.9, on Microsoft Windows [Version 10.0.19044.2251], locale en-GB)
    • Flutter version 3.3.9 on channel stable at C:\src\flutter\flutter                          
    • Upstream repository https://github.com/flutter/flutter.git                                 
    • Framework revision b8f7f1f986 (3 weeks ago), 2022-11-23 06:43:51 +0900                     
    • Engine revision 8f2221fbef                                                                 
    • Dart version 2.18.5                                                                        
    • DevTools version 2.15.0                                                                    
                                                                                                 
[√] Android toolchain - develop for Android devices (Android SDK version 33.0.0)                 
    • Android SDK at C:\Users\saifs\AppData\Local\Android\sdk
    • Platform android-33, build-tools 33.0.0
    • Java binary at: C:\Users\saifs\AppData\Local\JetBrains\Toolbox\apps\AndroidStudio\ch-0\213.7172.25.2113.9014738\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[X] Visual Studio - develop for Windows
    X Visual Studio not installed; this is necessary for Windows development.
      Download at https://visualstudio.microsoft.com/downloads/.
      Please install the "Desktop development with C++" workload, including all of its default components

[√] Android Studio (version 2021.3)
    • Android Studio at C:\Users\saifs\AppData\Local\JetBrains\Toolbox\apps\AndroidStudio\ch-0\213.7172.25.2113.9123335
    • Flutter plugin version 71.0.3
    • Dart plugin version 213.7433
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)

[√] Android Studio
    • Android Studio at C:\Users\saifs\AppData\Local\JetBrains\Toolbox\apps\AndroidStudio\ch-0\213.7172.25.2113.9014738
    • Flutter plugin version 70.2.3
    • Dart plugin version 213.7433
    • android-studio-dir = C:\Users\saifs\AppData\Local\JetBrains\Toolbox\apps\AndroidStudio\ch-0\213.7172.25.2113.9014738
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)

[√] IntelliJ IDEA Community Edition (version 2022.1)
    • IntelliJ at C:\Users\saifs\AppData\Local\JetBrains\Toolbox\apps\IDEA-C\ch-0\221.5080.210
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart

[√] VS Code (version 1.73.1)
    • VS Code at C:\Users\saifs\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension can be installed from:
       https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[√] Connected device (3 available)
    • SM A105F (mobile) • R58M65K2NGK • android-arm    • Android 11 (API 30)
    • Windows (desktop) • windows     • windows-x64    • Microsoft Windows [Version 10.0.19044.2251]
    • Chrome (web)      • chrome      • web-javascript • Google Chrome 108.0.5359.99

[√] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 1 category.
```

### Checklist before submitting a bug

- [X] I Google'd a solution and I couldn't find it
- [X] I searched on StackOverflow for a solution and I couldn't find it
- [X] I read the README.md file of the plugin
- [X] I'm using the latest version of the plugin
- [X] All dependencies are up to date with `flutter pub upgrade`
- [X] I did a `flutter clean`
- [X] I tried running the example project

### PR DESCRIPTION
**Pull request by k0T0z**
## Description

The plugin crashes on devices that don't have the corresponding sensor so this PR adds the code for checking if this corresponding sensor exists before setting the event stream.

## Related Issues

*Fix #1404*
*Resolve #1087*

## Checklist

- [x] I read the Contributor Guide and followed the process outlined there for submitting PRs.
- [x] I titled the PR using [Conventional Commits](https://www.conventionalcommits.org/en/v1.0.0).
- [x] I did not modify the `CHANGELOG.md` nor the `pubspec.yaml` files.
- [x] All existing and new tests are passing.
- [x] The analyzer (`flutter analyze`) does not report any problems on my PR.

## Breaking Change

Does your PR require plugin users to manually update their apps to accommodate your change?

- [ ] Yes, this is a breaking change (please indicate that with a `!` in the title as explained in [Conventional Commits](https://www.conventionalcommits.org/en/v1.0.0)).
- [x] No, this is *not* a breaking change (it's just for devices that don't have the corresponding sensor).

### CODE REVIEW

**Comment by nohli** [comment]
Hi, you marked the PR as ready for review, but there is only a todo so far.
Do you need any assistance?

**Comment by saifkandil** [comment]
> Hi, you marked the PR as ready for review, but there is only a todo so far.
> Do you need any assistance?

thank you nohli for reaching out, sorry bad it’s not ready for review yet but btw I added this todo to mark this place needs check before setting the event stream is this the right place in the code ?

**Comment by saifkandil** [comment]
No PlatformException is raised now because no event stream has been set, and also there's no exception raised to the user to inform him what's going on so please provide me some info on how to want this exception to be raised.

btw I don't know swift so didn't work on IOS native level, so what should be done for IOS? like learning swift? 😃 @nohli

**Comment by saifkandil** [comment]
Now it's completed for android please review @nohli @vbuberen. Note that I didn't work on ios native level yet so please provide me with some info on our next steps.

**Comment by saifkandil** [comment]
@nohli @vbuberen ?

**Comment by saifkandil** [comment]
why analyze crashes? @nohli 
```
$ flutter pub global run melos analyze
melos run analyze
  └> melos exec -c 5 -- \  dart analyze . --fatal-infos
     └> RUNNING

'melos' is not recognized as an internal or external command,
operable program or batch file.


melos run analyze
  └> melos exec -c 5 -- \  dart analyze . --fatal-infos
     └> FAILED
ScriptException: The script analyze failed to execute
pub finished with exit code 1
```

**Comment by nohli** [comment]
Please try step 3 of the [contributing guide](https://github.com/fluttercommunity/plus_plugins/blob/main/CONTRIBUTING.md#3-environment-setup) 😊

**Comment by saifkandil** [comment]
I did it as in doc but it still gives this error @nohli 
```
https://gist.github.com/saifkandil/6d2d9c6cec503091fa2f3d99fd23f481
```
I added the path to melos.bat to the environment vars because it won't run without ``flutter global run``, I don't understand this behavior actually

**Comment by nohli** [comment]
Regarding the error from gist, you can install [clang-format](https://formulae.brew.sh/formula/clang-format#default) via homebrew.

**Comment by saifkandil** [comment]
> Regarding the error from gist, you can install [clang-format](https://formulae.brew.sh/formula/clang-format#default) via homebrew.

okay I managed to run ``melos run format`` on macos but there's a problem with ``melos run analyze`` it works fine but it found issues with other packages what should I do? @nohli

**Comment by saifkandil** [comment]
All checks have passed successfully but still, there's a part missing, I can finish it tomorrow but feel free to review this PR @nohli

**Comment by saifkandil** [comment]
hello @mhadaily 
thanks for your email regarding gsoc, u told me to ping u if needed so please can you review this PR so it's merged so i can mention it in my proposal
again thanks

**Comment by vbuberen** [comment]
@saifkandil 
You don't need to spam people by tagging them. Everyone gets email notifications without multiple tags.

There is [an information in the repository description](https://github.com/fluttercommunity/plus_plugins#status) that maintainers reply on a best-effort basis and tagging multiple times will get nothing except being muted and ignored. This repo isn't somebody's daily job, so would be highly appreciated if you respected other people's time and understand that people might have some life or other priorities.

File: packages/sensors_plus/sensors_plus/android/src/main/kotlin/dev/fluttercommunity/plus/sensors/SensorsPlugin.kt [hunk 1]
```diff
@@ -33,29 +33,29 @@ class SensorsPlugin : FlutterPlugin {
...
+            sensorsManager,
+            Sensor.TYPE_ACCELEROMETER
         )
         accelerometerChannel.setStreamHandler(accelerationStreamHandler)
 
         userAccelChannel = EventChannel(messenger, USER_ACCELEROMETER_CHANNEL_NAME)
         linearAccelerationStreamHandler = StreamHandlerImpl(
-                sensorsManager,
-                Sensor.TYPE_LINEAR_ACCELERATION
+            sensorsManager,
```
Comment (saurabhkumar8112) [inline packages/sensors_plus/sensors_plus/android/src/main/kotlin/dev/fluttercommunity/plus/sensors/SensorsPlugin.kt:43]: I don't think formatting changes shall go in, as they differ from environment to environment. Let's keep it the same as it has been

File: packages/sensors_plus/sensors_plus/android/src/main/kotlin/dev/fluttercommunity/plus/sensors/SensorsPlugin.kt [hunk 2]
```diff
@@ -73,9 +73,12 @@ class SensorsPlugin : FlutterPlugin {
...
-        private const val ACCELEROMETER_CHANNEL_NAME = "dev.fluttercommunity.plus/sensors/accelerometer"
+        private const val ACCELEROMETER_CHANNEL_NAME =
+            "dev.fluttercommunity.plus/sensors/accelerometer"
         private const val GYROSCOPE_CHANNEL_NAME = "dev.fluttercommunity.plus/sensors/gyroscope"
-        private const val USER_ACCELEROMETER_CHANNEL_NAME = "dev.fluttercommunity.plus/sensors/user_accel"
-        private const val MAGNETOMETER_CHANNEL_NAME = "dev.fluttercommunity.plus/sensors/magnetometer"
+        private const val USER_ACCELEROMETER_CHANNEL_NAME =
+            "dev.fluttercommunity.plus/sensors/user_accel"
+        private const val MAGNETOMETER_CHANNEL_NAME =
+            "dev.fluttercommunity.plus/sensors/magnetometer"
```
Comment (saurabhkumar8112) [inline packages/sensors_plus/sensors_plus/android/src/main/kotlin/dev/fluttercommunity/plus/sensors/SensorsPlugin.kt:82]: since ""dev.fluttercommunity.plus/sensors/" is common in all channel_name, we can use it as a separate const value and append the sensor type later.
something like
```
private const prefix = "dev.fluttercommunity.plus/sensors/'
private const val ACCELEROMETER_CHANNEL_NAME = $prefix + "accelerometer"
```

File: packages/sensors_plus/sensors_plus/example/lib/main.dart [hunk 3]
```diff
@@ -144,6 +154,18 @@ class _MyHomePageState extends State<MyHomePage> {
             _accelerometerValues = <double>[event.x, event.y, event.z];
           });
         },
+        onError: (e) {
```
Comment (saurabhkumar8112) [inline packages/sensors_plus/sensors_plus/example/lib/main.dart:157]: can you also include stacktrace?

File: packages/sensors_plus/sensors_plus/example/lib/main.dart [hunk 4]
```diff
@@ -144,6 +154,18 @@ class _MyHomePageState extends State<MyHomePage> {
...
+          showDialog(
+              context: context,
+              builder: (context) {
+                return const AlertDialog(
```
Comment (saurabhkumar8112) [inline packages/sensors_plus/sensors_plus/example/lib/main.dart:161]: I think this choice be left to the develop, how they want to handle it and what UI they want to show, we should not add hardcoded UI

File: packages/sensors_plus/sensors_plus/android/src/main/kotlin/dev/fluttercommunity/plus/sensors/SensorsPlugin.kt (hunk 1 above)
Comment (vbuberen) [reply packages/sensors_plus/sensors_plus/android/src/main/kotlin/dev/fluttercommunity/plus/sensors/SensorsPlugin.kt:43]: Formatting isn't different as the project has editorconfig file in the root, so formatting should be the same unless the developer has overriding settings in IDE.

File: packages/sensors_plus/sensors_plus/example/lib/main.dart (hunk 4 above)
Comment (vbuberen) [reply packages/sensors_plus/sensors_plus/example/lib/main.dart:161]: You probably confusing the package with example app. In example app we can use whatever we want.

**Comment by vbuberen** [comment]
I will get to this PR next week. Sorry that it took so long.
Also, please disregard the review from @saurabhkumar8112

**Comment by saifkandil** [comment]
No problem, I can't wait to hear from you, thank you.

File: packages/sensors_plus/sensors_plus/ios/Classes/FLTSensorsPlusPlugin.m [hunk 5]
```diff
@@ -123,26 +123,45 @@ @implementation FLTAccelerometerStreamHandlerPlus
...
-                             // Multiply by gravity, and adjust sign values to
-                             // align with Android.
-                             if (_isCleanUp) {
-                               return;
-                             }
-                             sendTriplet(-acceleration.x * GRAVITY,
-                                         -acceleration.y * GRAVITY,
-                                         -acceleration.z * GRAVITY, eventSink);
-                           }];
+  switch (_motionManager.isAccelerometerAvailable) {
```
Comment (vbuberen) [inline packages/sensors_plus/sensors_plus/ios/Classes/FLTSensorsPlusPlugin.m:126]: As far as I know there are no modern iOS devices missing one of sensors like it is for some Android devices nowadays, so let's rollback changes related to iOS platform.

For example, here is a data about devices considered pretty old today:
https://www.quora.com/What-are-the-list-of-sensors-in-each-iPhone-iPad-version

File: packages/sensors_plus/sensors_plus/android/src/main/kotlin/dev/fluttercommunity/plus/sensors/SensorsPlugin.kt [hunk 6]
```diff
@@ -73,9 +73,12 @@ class SensorsPlugin : FlutterPlugin {
     }
 
     companion object {
-        private const val ACCELEROMETER_CHANNEL_NAME = "dev.fluttercommunity.plus/sensors/accelerometer"
+        private const val ACCELEROMETER_CHANNEL_NAME =
```
Comment (vbuberen) [inline packages/sensors_plus/sensors_plus/android/src/main/kotlin/dev/fluttercommunity/plus/sensors/SensorsPlugin.kt:76]: Are you sure that your IDE doen't override our editorconfig file with formatting style in the root of the repo?

File: packages/sensors_plus/sensors_plus/android/src/main/kotlin/dev/fluttercommunity/plus/sensors/StreamHandlerImpl.kt [hunk 7]
```diff
@@ -8,22 +8,48 @@ import io.flutter.plugin.common.EventChannel
...
-    private val sensor: Sensor by lazy {
-        sensorManager.getDefaultSensor(sensorType)
-    }
+    private var sensor: Sensor? = null
 
     override fun onListen(arguments: Any?, events: EventSink) {
-        sensorEventListener = createSensorEventListener(events)
-        sensorManager.registerListener(sensorEventListener, sensor, SensorManager.SENSOR_DELAY_NORMAL)
+        sensor = sensorManager.getDefaultSensor(sensorType)
+        when (sensor) {
```
Comment (vbuberen) [inline packages/sensors_plus/sensors_plus/android/src/main/kotlin/dev/fluttercommunity/plus/sensors/StreamHandlerImpl.kt:20]: Why not just use `if () else ()` here, considering that have just 2 cases?

File: packages/sensors_plus/sensors_plus/example/lib/main.dart [hunk 8]
```diff
@@ -7,11 +7,21 @@
 import 'dart:async';
 
 import 'package:flutter/material.dart';
+import 'package:flutter/services.dart';
 import 'package:sensors_plus/sensors_plus.dart';
 
 import 'snake.dart';
 
 void main() {
+  // Disable landscape mode
```
Comment (vbuberen) [inline packages/sensors_plus/sensors_plus/example/lib/main.dart:16]: Let's not disable landscape. We will address issues in landscape in another PR.

**Review by vbuberen — COMMENTED** [review]
Let's address a few issues that I mentioned and we will be ready to merge.

1. Check that `editorconfig` from the root is used for formatting Kotlin files.
2. Revert all iOS changes as there is no need to check for sensors availability there.
3. Remove locking to landscape in example app.

File: packages/sensors_plus/sensors_plus/android/src/main/kotlin/dev/fluttercommunity/plus/sensors/SensorsPlugin.kt (hunk 6 above)
Comment (vbuberen) [reply packages/sensors_plus/sensors_plus/android/src/main/kotlin/dev/fluttercommunity/plus/sensors/SensorsPlugin.kt:76]: Nevermind, all good.

**Comment by k0T0z** [comment]
Okay, I will work on it asap, I'm just buzy right now with my GSoC project, thanks

**Comment by vbuberen** [comment]
> Okay, I will work on it asap, I'm just buzy right now with my GSoC project, thanks

No worries, I am already working on changes.

**Comment by k0T0z** [comment]
I hope I helped as much as I can, if you need any help, just bing me here, thanks.

**Comment by vbuberen** [comment]
> I hope I helped as much as I can, if you need any help, just bing me here, thanks.

Absolutely. You helped a lot by reporting and working on the solution. Thanks a lot for your contribution. I will try to release the fix somewhere this week.
