### PR TITLE
fix(share_plus): Recover ShareSuccessManager state after error

### LINKED ISSUE #1351: [Bug]: prior share-sheet did not call back, did you await it? Maybe use non-result variant
### Platform

android 10

### Plugin

share_plus

### Version

6.2.0

### Flutter SDK

3.0.4

### Steps to reproduce

call this

```
const logFileName = 'log.txt';
Future<String> get logFilePath async =>
    '${await getApplicationDocumentsDirectory().then((value) => value.path)}/$logFileName';
Share.shareXFiles([XFile(await logFilePath)])
```

### Code Sample

_No response_

### Logs

```shell
E/flutter (13841): [ERROR:flutter/lib/ui/ui_dart_state.cc(198)] Unhandled Exception: PlatformException(Share callback error, prior share-sheet did not call back, did you await it? Maybe use non-result variant, null, null)
E/flutter (13841): #0      StandardMethodCodec.decodeEnvelope
package:flutter/…/services/message_codecs.dart:607
E/flutter (13841): #1      MethodChannel._invokeMethod
package:flutter/…/services/platform_channel.dart:167
E/flutter (13841): <asynchronous suspension>
E/flutter (13841): #2      MethodChannelShare.shareFilesWithResult
package:share_plus_platform_interface/method_channel/method_channel_share.dart:134
E/flutter (13841): <asynchronous suspension>
E/flutter (13841):
```

### Flutter Doctor

```shell
[✓] Flutter (Channel stable, 3.0.4, on macOS 12.5.1 21G83 darwin-arm, locale en-UA)
    • Flutter version 3.0.4 at /Users/illia/Development/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 85684f9300 (5 months ago), 2022-06-30 13:22:47 -0700
    • Engine revision 6ba2af10bb
    • Dart version 2.17.5
    • DevTools version 2.12.2
```

### Checklist before submitting a bug

- [X] I Google'd a solution and I couldn't find it
- [X] I searched on StackOverflow for a solution and I couldn't find it
- [X] I read the README.md file of the plugin
- [X] I'm using the latest version of the plugin
- [X] All dependencies are up to date with `flutter pub upgrade`
- [X] I did a `flutter clean`
- [X] I tried running the example project

### LINKED ISSUE #1612: [Bug]: Share.shareXFiles is not working on my Android 11 device but Share.shareFiles is working
### Platform

Android 11

### Plugin

share_plus

### Version

6.3.0

### Flutter SDK

3.7.6

### Steps to reproduce

I am calling : 

```
 await Share.shareFiles([(filePath)], subject: "A nice subject");
```

And it's working fine, but this method is deprecated. 

So i have tried to use : 

``` 
await Share.shareXFiles([XFile(filePath)], subject: "A nice subject");
```

And here is the output : `PlatformException(Share callback error, prior share-sheet did not call back, did you await it? Maybe use non-result variant, null, null)`

With the exact same `filePath`

The only thing i have found on Google which was not helpful was : `https://stackoverflow.com/questions/71855220/flutter-package-share-plus-unexpected-async-await-behaviour` but this doesn't seem to match my behavior since it's working with the deprecated method.

### Code Sample

```dart
call `await Share.shareXFiles([XFile(filePath)], subject: "A nice subject")` and see the error.
```

### Logs

```shell
There is nothing helpful so i am attaching the only log i have got : 

`PlatformException(Share callback error, prior share-sheet did not call back, did you await it? Maybe use non-result variant, null, null)`
```

### Flutter Doctor

```shell
[✓] Flutter (Channel stable, 3.7.6, on macOS 13.2.1 22D68 darwin-x64, locale fr-FR)
    • Flutter version 3.7.6 on channel stable at /Users/foxtom/Desktop/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 12cb4eb7a0 (10 days ago), 2023-03-01 10:29:26 -0800
    • Engine revision ada363ee93
    • Dart version 2.19.3
    • DevTools version 2.20.1

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.1)
    • Android SDK at /Users/foxtom/Library/Android/sdk
    • Platform android-33, build-tools 33.0.1
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.15+0-b2043.56-8887301)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14C18
    • CocoaPods version 1.12.0

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2022.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.15+0-b2043.56-8887301)

[✓] VS Code (version 1.76.1)
    • VS Code at /Users/foxtom/Desktop/Visual Studio Code.app/Contents
    • Flutter extension version 3.46.0

[✓] Connected device (3 available)
    • moto g 8 power (mobile) • adb-ZY22BNDW2C-yyjDO7._adb-tls-connect._tcp. • android-arm64  • Android 11 (API 30)
    • macOS (desktop)         • macos                                        • darwin-x64     • macOS 13.2.1 22D68 darwin-x64
    • Chrome (web)            • chrome                                       • web-javascript • Google Chrome 110.0.5481.177

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```

### Checklist before submitting a bug

- [X] I Google'd a solution and I couldn't find it
- [X] I searched on StackOverflow for a solution and I couldn't find it
- [X] I read the README.md file of the plugin
- [X] I'm using the latest version of the plugin
- [X] All dependencies are up to date with `flutter pub upgrade`
- [X] I did a `flutter clean`
- [X] I tried running the example project

### LINKED ISSUE #1936: [Bug]: share_plus exception prevents further use
### Platform

Android 13

### Plugin

share_plus

### Version

7.0.2

### Flutter SDK

3.10.5

### Steps to reproduce

1. Ask share_plus to share a file that doesn't exist.
2. Ask share_plus to share a file that exists.

From then on, any attempt to share is met with the error below.

### Code Sample

_No response_

### Logs

```shell
E/flutter ( 6836): [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: PlatformException(Share callback error, prior share-sheet did not call back, did you await it? Maybe use non-result variant, null, null)
E/flutter ( 6836): #0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:652:7)
E/flutter ( 6836): #1      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:310:18)
E/flutter ( 6836): <asynchronous suspension>
E/flutter ( 6836): #2      MethodChannelShare.shareFilesWithResult (package:share_plus_platform_interface/method_channel/method_channel_share.dart:134:9)
E/flutter ( 6836): <asynchronous suspension>
E/flutter ( 6836):
```

### Flutter Doctor

```shell
[√] Flutter (Channel stable, 3.10.5, on Microsoft Windows [Version 10.0.19045.3086], locale fr-BE)
    • Flutter version 3.10.5 on channel stable at D:\Code\Flutter\sdk\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 796c8ef792 (3 weeks ago), 2023-06-13 15:51:02 -0700
    • Engine revision 45f6e00911
    • Dart version 3.0.5
    • DevTools version 2.23.1

[√] Windows Version (Installed version of Windows is version 10 or higher)

[√] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at C:\Users\user\AppData\Local\Android\sdk
    • Platform android-33, build-tools 30.0.3
    • Java binary at: C:\Program Files\Android\Android Studio 2022\jbr\bin\java
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-b2043.56-9586694)
    • All Android licenses accepted.

[√] Visual Studio - develop for Windows (Visual Studio Community 2022 17.1.6)
    • Visual Studio at C:\Program Files\Microsoft Visual Studio\2022\Community
    • Visual Studio Community 2022 version 17.1.32421.90
    • Windows 10 SDK version 10.0.19041.0

[√] Android Studio (version 2021.2)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+7-b1504.28-7817840)

[√] Android Studio (version 2022.2)
    • Android Studio at C:\Program Files\Android\Android Studio 2022
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-b2043.56-9586694)

[√] VS Code (version 1.77.3)
    • VS Code at C:\Users\user\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.44.0

[√] VS Code, 64-bit edition (version 1.79.1)
    • VS Code at C:\Program Files\Microsoft VS Code
    • Flutter extension version 3.44.0

[√] Connected device (2 available)
    • sdk gphone64 x86 64 (mobile) • emulator-5554 • android-x64 • Android 13 (API 33) (emulator)
    • Windows (desktop)            • windows       • windows-x64 • Microsoft Windows [Version 10.0.19045.3086]

[√] Network resources
    • All expected network resources are available.

• No issues found!
```

### Checklist before submitting a bug

- [X] I Google'd a solution and I couldn't find it
- [X] I searched on StackOverflow for a solution and I couldn't find it
- [X] I read the README.md file of the plugin
- [X] I'm using the latest version of the plugin
- [X] All dependencies are up to date with `flutter pub upgrade`
- [X] I did a `flutter clean`
- [X] I tried running the example project

### LINKED ISSUE #2461: [Question]: Unhandled Exception: PlatformException(Share callback error, prior share-sheet did not call back, did you await it? Maybe use non-result variant, null, null)
### What is your question?

I use flutter version 3.16.3. flutter doctor and everything other is ok.

Here is some brief codes:
String dir = (await getTemporaryDirectory()).path;
String saveFileName = user.userName.replaceAll('/', '_')+ Constant.SAVE_FORMAT;
File saveFile = File('$dir/$saveFileName' );
Share.shareXFiles([XFile(saveFile.path)], text: 'sharing');

Here is the error log:
I/flutter ( 8533): parent: /storage/emulated/0/Android/data
I/flutter ( 8533): /storage/emulated/0/Android/data/com.tencent.mm/MicroMsg/Download
I/flutter ( 8533): delFile: /storage/emulated/0/Android/data/com.tencent.mm/MicroMsg/Download/B.E.G. DALI-LINK.beglnk
E/flutter ( 8533): [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: PlatformException(Share callback error, prior share-sheet did not call back, did you await it? Maybe use non-result variant, null, null)
E/flutter ( 8533): #0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:651:7)
E/flutter ( 8533): #1      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:322:18)
E/flutter ( 8533): <asynchronous suspension>
E/flutter ( 8533): #2      MethodChannelShare.shareFilesWithResult (package:share_plus_platform_interface/method_channel/method_channel_share.dart:140:9)
E/flutter ( 8533): <asynchronous suspension>

### Checklist before submitting a question

- [X] I searched issues in this repository and couldn't find such bug/problem
- [X] I Google'd a solution and I couldn't find it
- [X] I searched on StackOverflow for a solution and I couldn't find it
- [X] I read the README.md file of the plugin
- [X] I am using the latest version of the plugin
- [X] All dependencies are up to date with `flutter pub upgrade`
- [X] I did a `flutter clean`
- [X] I tried running the example project

### LINKED ISSUE #2530: [Bug]: share_plus ANR - Input dispatching timed out
### Platform

Android 10, 11, 12, 13

### Plugin

share_plus

### Version

7.2.1

### Flutter SDK

3.16.3

### Steps to reproduce

In the Google Play console I'm getting a number of ANRs.

The crash report lists the problem as:

The main thread was busy performing an I/O operation. This could be caused by network or file access (especially compressed files), but can also be caused by operations such as ClassLoader.loadClass.

The error I'm getting is:
```PlatformException(Share callback error, prior share-sheet did not call back, did you await it? Maybe use non-result variant, null, null)```

### Code Sample

```dart
await Share.shareXFiles([XFile(videoPath)]);
```

### Logs

```shell
This could be related to https://github.com/fluttercommunity/plus_plugins/issues/2398
```

### Flutter Doctor

```shell
[√] Flutter (Channel stable, 3.16.3, on Microsoft Windows [Version 10.0.19045.3930], locale en-US)
    • Flutter version 3.16.3 on channel stable at C:\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision b0366e0a3f (7 weeks ago), 2023-12-05 19:46:39 -0800
    • Engine revision 54a7145303
    • Dart version 3.2.3
    • DevTools version 2.28.4

[√] Windows Version (Installed version of Windows is version 10 or higher)

[√] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at C:\Users\Acer\AppData\Local\Android\sdk
    • Platform android-UpsideDownCakePrivacySandbox, build-tools 34.0.0
    • Java binary at: C:\Program Files\Android\Android Studio\jbr\bin\java
    • Java version OpenJDK Runtime Environment (build 17.0.7+0-b2043.56-10550314)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop Windows apps (Visual Studio Community 2022 17.0.2)
    • Visual Studio at C:\Program Files\Microsoft Visual Studio\2022\Community
    • Visual Studio Community 2022 version 17.0.31919.166
    • Windows 10 SDK version 10.0.19041.0

[√] Android Studio (version 2023.1)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • android-studio-dir = C:\Program Files\Android\Android Studio
    • Java version OpenJDK Runtime Environment (build 17.0.7+0-b2043.56-10550314)

[√] VS Code, 64-bit edition (version 1.85.1)
    • VS Code at C:\Program Files\Microsoft VS Code
    • Flutter extension version 3.56.0

[√] Connected device (4 available)
    • Z5157V (mobile)   • 320415126524 • android-arm    • Android 10 (API 29)
    • Windows (desktop) • windows      • windows-x64    • Microsoft Windows [Version 10.0.19045.3930]
    • Chrome (web)      • chrome       • web-javascript • Google Chrome 120.0.6099.225
    • Edge (web)        • edge         • web-javascript • Microsoft Edge 119.0.2151.93

[√] Network resources
    • All expected network resources are available.

• No issues found!
```
```


### Checklist before submitting a bug

- [X] I searched issues in this repository and couldn't find such bug/problem
- [X] I Google'd a solution and I couldn't find it
- [X] I searched on StackOverflow for a solution and I couldn't find it
- [X] I read the README.md file of the plugin
- [X] I'm using the latest version of the plugin
- [X] All dependencies are up to date with `flutter pub upgrade`
- [X] I did a `flutter clean`
- [X] I tried running the example project

### PR DESCRIPTION
**Pull request by miquelbeltran**
## Description

- Looking at issues reported in #1936 and #1351, I figured out that the `ShareSuccessManager` was in a bad state which blocked users from continuing using the plugin.
- The `ShareSuccessManager` checks the state of the current callback state, and fails if a callback was never executed. This is problematic because causes this state to be never recover after an error happened.
- The problem is that, on error, `onActivityResult` is never called, so the state is never restored.
- To solve this problem, I introduced a `clear()` method that will reset the state, only call to this method in cases we catch an error.
- did a refactor, and moved things a bit, simplifying the code of the `MethodCallHandler`.
- to test this, I call `shareXFiles` with bad `XFile` (wrong paths), which causes an exception. Then I call the `share` methods normally and still works, both with result and without.
- In the future, if we find other edge cases where `ShareSuccessManager` is in a bad state, we can use the clear method in those edge cases to clean up the state.
- This PR supersedes #2446 as it provides a more precise way to handle errors, while still maintaining the old functionality intact.

## Related Issues

- Fix #1351 
- Fix #1612
- Fix #1936
- Fix #2461
- Fix #2530

## Checklist

- [x] I read the [Contributor Guide](https://github.com/fluttercommunity/plus_plugins/blob/main/CONTRIBUTING.md) and followed the process outlined there for submitting PRs.
- [x] I titled the PR using [Conventional Commits](https://www.conventionalcommits.org/en/v1.0.0).
- [x] I did not modify the `CHANGELOG.md` nor the plugin version in `pubspec.yaml` files.
- [x] All existing and new tests are passing.
- [x] The analyzer (`flutter analyze`) does not report any problems on my PR.

## Breaking Change

Does your PR require plugin users to manually update their apps to accommodate your change?

- [ ] Yes, this is a breaking change (please indicate that with a `!` in the title as explained in [Conventional Commits](https://www.conventionalcommits.org/en/v1.0.0)).
- [x] No, this is *not* a breaking change.

### CODE REVIEW

File: packages/share_plus/share_plus/android/src/main/kotlin/dev/fluttercommunity/plus/share/MethodCallHandler.kt [hunk 1]
```diff
@@ -8,72 +8,68 @@ import java.io.IOException
 /** Handles the method calls for the plugin.  */
 internal class MethodCallHandler(
     private val share: Share,
-    private val manager: ShareSuccessManager
+    private val manager: ShareSuccessManager,
 ) : MethodChannel.MethodCallHandler {
 
     override fun onMethodCall(call: MethodCall, result: MethodChannel.Result) {
+        expectMapArguments(call)
+
```
Comment (miquelbeltran) [inline packages/share_plus/share_plus/android/src/main/kotlin/dev/fluttercommunity/plus/share/MethodCallHandler.kt:16]: Moved to the top since it is common on all methods

File: packages/share_plus/share_plus/android/src/main/kotlin/dev/fluttercommunity/plus/share/MethodCallHandler.kt [hunk 2]
```diff
@@ -8,72 +8,68 @@ import java.io.IOException
...
-                    withResult= false
-                )
-                if (!isWithResult) {
-                    result.success(null)
-                }
-            }
-            "share", "shareWithResult" -> {
-                expectMapArguments(call)
-                if (isWithResult && !manager.setCallback(result)) return
+        if (isWithResult && !manager.setCallback(result)) return
```
Comment (miquelbeltran) [inline packages/share_plus/share_plus/android/src/main/kotlin/dev/fluttercommunity/plus/share/MethodCallHandler.kt:23]: Moved to the top since it is common for all methods as well.

File: packages/share_plus/share_plus/android/src/main/kotlin/dev/fluttercommunity/plus/share/MethodCallHandler.kt [hunk 3]
```diff
@@ -8,72 +8,68 @@ import java.io.IOException
...
-                    result.error("Share failed", e.message, null)
+                    success(isWithResult, isResultRequested, result)
                 }
+
+                else -> result.notImplemented()
+            }
+        } catch (e: IOException) {
+            manager.clear()
+            result.error("Share failed", e.message, null)
+        }
```
Comment (miquelbeltran) [inline packages/share_plus/share_plus/android/src/main/kotlin/dev/fluttercommunity/plus/share/MethodCallHandler.kt:59]: Surround all the share calls with a try/catch that will call to `manager.clear()`, which fixes the actual bug, as well as return the error result.

File: packages/share_plus/share_plus/android/src/main/kotlin/dev/fluttercommunity/plus/share/MethodCallHandler.kt [hunk 4]
```diff
@@ -8,72 +8,68 @@ import java.io.IOException
...
+    private fun success(
+        isWithResult: Boolean,
+        isResultRequested: Boolean,
+        result: MethodChannel.Result
+    ) {
+        if (!isWithResult) {
+            if (isResultRequested) {
+                result.success("dev.fluttercommunity.plus/share/unavailable")
+            } else {
+                result.success(null)
```
Comment (miquelbeltran) [inline packages/share_plus/share_plus/android/src/main/kotlin/dev/fluttercommunity/plus/share/MethodCallHandler.kt:71]: Just moved all the `result.success()` code to a common method to avoid code duplication in the switch

File: packages/share_plus/share_plus/android/src/main/kotlin/dev/fluttercommunity/plus/share/MethodCallHandler.kt [hunk 5]
```diff
@@ -8,72 +8,68 @@ import java.io.IOException
...
-                    result.error("Share failed", e.message, null)
+                    success(isWithResult, isResultRequested, result)
                 }
+
+                else -> result.notImplemented()
+            }
+        } catch (e: Throwable) {
+            manager.clear()
+            result.error("Share failed", e.message, e)
+        }
```
Comment (miquelbeltran) [inline packages/share_plus/share_plus/android/src/main/kotlin/dev/fluttercommunity/plus/share/MethodCallHandler.kt:59]: Catch _all_ errors from share methods, pass them up to the Flutter layer, but before also call to `manager.clear()` to avoid the deadlock state in `ShareSuccessManager`.

This can be tested simply by calling

```dart
    await Share.shareXFiles(
      [XFile('/wrong/file')],
      text: text,
    );
```
then the user sees something like
```
E/flutter (29015): [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: PlatformException(Share failed, /wrong/file: The source file doesn't exist.,
```
however, they will be able to use the share methods again later on because `manager.clear()` was called.

**Review by vbuberen — APPROVED** [review]
Thanks for tackling this bug

**Comment by vbuberen** [comment]
I believe it also closes https://github.com/fluttercommunity/plus_plugins/issues/2515 even though the report didn't bother to provide meaningful details requested.
