### PR TITLE
fix(share_plus): `mime` compatible with v2 (v1 still supported)

### LINKED ISSUE #3308: [Request]: Bump mime to v2
### Plugin

share_plus

### Use case

`share_plus` is preventing us from upgrading our packages:
```
flutter pub upgrade --major-versions

Because every version of <some_package> from git depends on mime ^2.0.0 and share_plus >=7.0.0 depends on mime ^1.0.4, <some_package> from git is incompatible with share_plus >=7.0.0.
```

### Proposal

Bump `mime` from `share_plus` to v2

### PR DESCRIPTION
**Pull request by mafreud**
## Description
Update mime to v2

## Related Issues
- *Fix #3308

## Checklist

- [ ] I read the [Contributor Guide](https://github.com/fluttercommunity/plus_plugins/blob/main/CONTRIBUTING.md) and followed the process outlined there for submitting PRs.
- [ ] I titled the PR using [Conventional Commits](https://www.conventionalcommits.org/en/v1.0.0).
- [ ] I did not modify the `CHANGELOG.md` nor the plugin version in `pubspec.yaml` files.
- [ ] All existing and new tests are passing.
- [ ] The analyzer (`flutter analyze`) does not report any problems on my PR.

## Breaking Change

Does your PR require plugin users to manually update their apps to accommodate your change?

- [ ] Yes, this is a breaking change (please indicate that with a `!` in the title as explained in [Conventional Commits](https://www.conventionalcommits.org/en/v1.0.0)).
- [x] No, this is *not* a breaking change.

### CODE REVIEW

**Comment by miquelbeltran** [comment]
The code needs to updated to verify that `extensionFromMine` does not return `null`.

File: packages/share_plus/share_plus_platform_interface/lib/method_channel/method_channel_share.dart [hunk 1]
```diff
@@ -130,11 +130,10 @@ class MethodChannelShare extends SharePlatform {
       return file;
     } else {
       tempRoot ??= (await getTemporaryDirectory()).path;
-      var extension = extensionFromMime(file.mimeType ?? 'octet-stream');
-
-      // TODO: As soon as the mime package fixes the image/jpe issue, remove this line immediately
-      // Reference: https://github.com/dart-lang/mime/issues/55
-      extension = extension == "jpe" ? "jpeg" : extension;
```
Comment (miquelbeltran) [inline packages/share_plus/share_plus_platform_interface/lib/method_channel/method_channel_share.dart:137]: This issue has been long fixed
