### PR TITLE
fix(device_info_plus): Update exports to avoid web compatibility issues

### LINKED ISSUE #1651: [device_info_plus]: According to package analysis, device_info_plus 8.1.0 is not Web compatible??
### What is your question?

I want my Dart package, [fluttery framework](https://pub.dev/packages/fluttery_framework), to be Web-compatible, but it appears device_info_plus is preventing this.

When I publish it to Pub.dev, the package analysis states it's not Web compatible. 

However, it's  [device_info_plus](https://pub.dev/packages/device_info_plus) itself that imports device_info_plus_linux which eventually imports dart:io.

dart:io is not Web compatible! (see Platform support).

That's beyond my control! Is it not?
And so my question is, how can I use device_info_plus and be Web-compatible at the same time?

I'm importing the plus plugin in the following file:
package:fluttery_framework/src/controller/device_info.dart
[import](https://github.com/AndriousSolutions/fluttery_framework/blob/master/lib/src/controller/device_info.dart#L13)
When the app starts up, the plugin is then called:
[info](https://github.com/AndriousSolutions/fluttery_framework/blob/master/lib/src/controller/device_info.dart#L39)

## Possible Solution
I was looking through the [source code](https://github.com/fluttercommunity/plus_plugins/blob/main/packages/device_info_plus/device_info_plus/lib/device_info_plus.dart#L28):

Would introducing a conditional import on the 'linux' file as well as the 'Windows' file be helpful:?:
[image](https://github.com/fluttercommunity/plus_plugins/blob/main/packages/device_info_plus/device_info_plus/lib/device_info_plus.dart#L28)

This will allow device_info_plus to be used and supported on all 6 platforms.

## Package Analysis
<details>
  <summary>Platform support</summary>

```
20/20 points: Supports 5 of 6 possible platforms (iOS, Android, Web, Windows, MacOS, Linux)
✓ Android
✓ iOS
✓ Windows
✓ Linux
✓ MacOS
These platforms are not supported:

Package not compatible with platform Web
Because:

package:fluttery_framework/controller.dart that imports:
package:fluttery_framework/src/controller/device_info.dart that imports:
package:device_info_plus/device_info_plus.dart that imports:
package:device_info_plus/src/device_info_plus_linux.dart that imports:
package:file/local.dart that imports:
package:file/src/backends/local.dart that imports:
package:file/src/backends/local/local_file_system.dart that imports:
package:file/src/backends/local/local_link.dart that imports:
package:file/src/backends/local/local_file_system_entity.dart that imports:
package:file/src/backends/local/local_file.dart that imports:
package:file/src/io.dart that imports:
dart:io
```

</details>

## System Info

package: [fluttery framework](https://pub.dev/packages/fluttery_framework/score)
plugin: [device_info_plus 8.1.0](https://pub.dev/packages/device_info_plus)
<details>
  <summary>flutter doctor -v</summary>

```
[√] Flutter (Channel stable, 3.7.8, on Microsoft Windows [Version 10.0.22621.1413], locale en-CA)
    • Flutter version 3.7.8 on channel stable at C:\Programs\Tools\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 90c64ed42b (7 days ago), 2023-03-21 11:27:08 -0500
    • Engine revision 9aa7816315
    • Dart version 2.19.5
    • DevTools version 2.20.1

[√] Windows Version (Installed version of Windows is version 10 or higher)

[√] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
    • Android SDK at C:\Programs\Tools\Android\SDK
    • Platform android-33, build-tools 33.0.0
    • ANDROID_HOME = C:\Programs\Tools\Android\SDK
    • ANDROID_SDK_ROOT = C:\Programs\Tools\Android\SDK
    • Java binary at: C:\Programs\Tools\Android\Studio\jbr\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.15+0-b2043.56-9505619)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[X] Visual Studio - develop for Windows
    X Visual Studio not installed; this is necessary for Windows development.
      Download at https://visualstudio.microsoft.com/downloads/.
      Please install the "Desktop development with C++" workload, including all of its default components

[√] Android Studio (version 2022.1)
    • Android Studio at C:\Programs\Tools\Android\Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.15+0-b2043.56-9505619)

[√] IntelliJ IDEA Community Edition (version 2019.1)
    • IntelliJ at C:\Programs\Tools\Dart\IntelliJ
    • Flutter plugin version 35.0.3
    • Dart plugin version 191.7019

[√] Connected device (3 available)
    • Windows (desktop) • windows • windows-x64    • Microsoft Windows [Version 10.0.22621.1413]
    • Chrome (web)      • chrome  • web-javascript • Google Chrome 111.0.5563.146
    • Edge (web)        • edge    • web-javascript • Microsoft Edge 111.0.1661.41

[√] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 1 category.

```

</details>

## Steps to Reproduce

Publishing with the latest version of device_info_plus.

**Expected results:**  20/20 points: Supports 6 of 6 possible platforms 

**Actual results:**       20/20 points: Supports 5 of 6 possible platforms 

Please, I am at a loss.  What am I missing here?

[analysis](https://pub.dev/packages/fluttery_framework/score)

### Checklist before submitting a question

- [X] I Google'd a solution and I couldn't find it
- [X] I searched on StackOverflow for a solution and I couldn't find it
- [X] I read the README.md file of the plugin
- [X] I am using the latest version of the plugin
- [X] All dependencies are up to date with `flutter pub upgrade`
- [X] I did a `flutter clean`
- [X] I tried running the example project

### PR DESCRIPTION
**Pull request by vbuberen**
## Description

According to #1651 `device_info_plus` might cause some analyzer issues to other packages which use the plugin. After looking at code it looks like we already had a conditional export for windows part, so this PR adds the same condition to linux part to be sure that there are no unsupported libraries used for web (at least from package analyzer point of view). 

## Related Issues

Fixes #1651 

## Breaking Change

Does your PR require plugin users to manually update their apps to accommodate your change?

- [ ] Yes, this is a breaking change (please indicate that with a `!` in the title as explained in [Conventional Commits](https://www.conventionalcommits.org/en/v1.0.0)).
- [x] No, this is *not* a breaking change.

### CODE REVIEW

File: packages/device_info_plus/device_info_plus/lib/device_info_plus.dart [hunk 1]
```diff
@@ -25,7 +25,8 @@ export 'src/model/macos_device_info.dart';
 export 'src/model/web_browser_info.dart';
 export 'src/model/windows_device_info.dart';
 
-export 'src/device_info_plus_linux.dart';
+export 'src/device_info_plus_linux.dart'
+    if (dart.library.html) 'src/device_info_plus_web.dart';
 export 'src/device_info_plus_windows.dart'
     if (dart.library.html) 'src/device_info_plus_web.dart';
```
Comment (nohli) [inline packages/device_info_plus/device_info_plus/lib/device_info_plus.dart:31]: Can we chain two if clauses, instead of exporting the same library twice?

Comment (vbuberen) [reply packages/device_info_plus/device_info_plus/lib/device_info_plus.dart:31]: No, unfortunately we can't. As far as I understand there are no issues with such export or, otherwise, we would see failing builds.

Comment (vbuberen) [reply packages/device_info_plus/device_info_plus/lib/device_info_plus.dart:31]: Going to merge to release new versions in nearest time
