### PR TITLE
fix(device_info_plus)!: fixed webasm compliance

### LINKED ISSUE #3253: [Bug]: illegal cast in device_info_plus when compiled to Wasm
### Platform

web in asm mode 

### Plugin

device_info_plus

### Version

10.1.2

### Flutter SDK

3.24.2 (stable)

### Steps to reproduce

use device_info_plus in a project compile for webasm. It compiles, but on the execution you got illegal cast errors.

1. compile to wasm (see https://docs.flutter.dev/platform-integration/web/wasm for details)
`flutter build web --wasm --no-strip-wasm`
2. serve the result
```
cd build/web
dhttpd '--headers=Cross-Origin-Embedder-Policy=credentialless;Cross-Origin-Opener-Policy=same-origin'
```
3. open the app in your browser and check its console

### Code Sample

```dart
void main() async {
  final BaseDeviceInfo deviceInfo = await DeviceInfoPlugin().deviceInfo;
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return Container();
  }
}
```

### Logs

```shell
Webasm can't run in flutter -run --verbose. This log is from the web browser.

main.dart.wasm:0x41ed24 Uncaught RuntimeError: illegal cast
    at DeviceInfoPlusWebPlugin.deviceInfo (main.dart.wasm:0x41ed24)
    at DeviceInfoPlugin.webBrowserInfo inner (main.dart.wasm:0x41e9ed)
    at DeviceInfoPlugin.deviceInfo inner (main.dart.wasm:0x41e8cf)
    at run inner (main.dart.wasm:0x23551b)
    at _awaitHelperWithTypeCheck closure at org-dartlang-sdk:///dart-sdk/lib/_internal/wasm/lib/async_patch.dart:97:16 (main.dart.wasm:0x233ee2)
    at closure wrapper at org-dartlang-sdk:///dart-sdk/lib/_internal/wasm/lib/async_patch.dart:97:16 trampoline (main.dart.wasm:0x233f4a)
    at _RootZone.runUnary (main.dart.wasm:0x1e0c26)
    at _Future._propagateToListeners (main.dart.wasm:0x1e0565)
    at _Future._completeWithValue (main.dart.wasm:0x1e019c)
    at _Future._asyncCompleteWithValue closure at org-dartlang-sdk:///dart-sdk/lib/async/future_impl.dart:735:29 (main.dart.wasm:0x1e0147)
```

### Flutter Doctor

```shell
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.24.2, on macOS 14.6.1 23G93 darwin-arm64, locale fr-FR)
[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 15.4)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2024.1)
[✓] IntelliJ IDEA Ultimate Edition (version 2024.2.1)
[✓] VS Code (version 1.93.0)
[✓] VS Code (version 1.92.0-insider)
[✓] Connected device (3 available)
[✓] Network resources
```

### Checklist before submitting a bug

- [X] I searched issues in this repository and couldn't find such bug/problem
- [X] I Google'd a solution and I couldn't find it
- [X] I searched on StackOverflow for a solution and I couldn't find it
- [X] I read the README.md file of the plugin
- [X] I'm using the latest version of the plugin
- [X] All dependencies are up to date with `flutter pub upgrade`
- [X] I did a `flutter clean`
- [X] I tried running the example project

### PR DESCRIPTION
**Pull request by arnaudruffin**
## Description

This PR allows device_info_plus to be used in a web project compiled to webasm.

For that a type had to be changed (devicememory became a double?) and one converted from JStype to dart type.
I also took the liberty to update the example "index.html" file, as it was based on a deprecated template and not compatible with webasm compilation.

Most of this commit is a copy of what was done in https://github.com/fluttercommunity/plus_plugins/pull/3161 by @GiacomoPignoni . Credits go to him.

## Related Issues
- *Fix #3253*

## Checklist

- [x] I read the [Contributor Guide](https://github.com/fluttercommunity/plus_plugins/blob/main/CONTRIBUTING.md) and followed the process outlined there for submitting PRs.
- [x] I titled the PR using [Conventional Commits](https://www.conventionalcommits.org/en/v1.0.0).
- [x] I did not modify the `CHANGELOG.md` nor the plugin version in `pubspec.yaml` files.
- [x] All existing and new tests are passing.
- [ ] The analyzer (`flutter analyze`) does not report any problems on my PR. => not directly on my modifications

## Breaking Change

Does your PR require plugin users to manually update their apps to accommodate your change?

- [x] Yes, this is a breaking change (please indicate that with a `!` in the title as explained in [Conventional Commits](https://www.conventionalcommits.org/en/v1.0.0)).
- [ ] No, this is *not* a breaking change.

### CODE REVIEW

File: packages/device_info_plus/device_info_plus/lib/src/device_info_plus_web.dart [hunk 1]
```diff
@@ -30,7 +31,7 @@ class DeviceInfoPlusWebPlugin extends DeviceInfoPlatform {
           'appVersion': _navigator.appVersion,
           'deviceMemory': _navigator.deviceMemory,
           'language': _navigator.language,
-          'languages': _navigator.languages,
+          'languages': _navigator.languages.toDart,
```
Comment (miquelbeltran) [inline packages/device_info_plus/device_info_plus/lib/src/device_info_plus_web.dart:34]: Is this change maybe unrelated to the rest of the PR?

File: packages/device_info_plus/device_info_plus/lib/src/device_info_plus_web.dart [hunk 2]
```diff
@@ -47,7 +48,6 @@ class DeviceInfoPlusWebPlugin extends DeviceInfoPlatform {
 
 /// Property is missing.
 /// Ticket: https://github.com/dart-lang/web/issues/192
-/// Probably won't be an int? in the future!
 extension on html.Navigator {
-  external int? get deviceMemory;
+  external double? get deviceMemory;
```
Comment (miquelbeltran) [inline packages/device_info_plus/device_info_plus/lib/src/device_info_plus_web.dart:52]: Looking at the linked ticket, it is possible that `deviceMemory` is now part of the `web` package navigator, but haven't looked into that yet.

File: packages/device_info_plus/device_info_plus/lib/src/device_info_plus_web.dart (hunk 1 above)
Comment (arnaudruffin) [reply packages/device_info_plus/device_info_plus/lib/src/device_info_plus_web.dart:34]: No, this is needed for webasm compilation

File: packages/device_info_plus/device_info_plus/lib/src/device_info_plus_web.dart (hunk 2 above)
Comment (arnaudruffin) [reply packages/device_info_plus/device_info_plus/lib/src/device_info_plus_web.dart:52]: I saw the linked ticket but I decided to focus on the webasm compilation. Do you need me to add something regarding this?

Comment (miquelbeltran) [reply packages/device_info_plus/device_info_plus/lib/src/device_info_plus_web.dart:52]: Yes, I think this extension can be replaced by web's `deviceMemory`: https://pub.dev/documentation/web/latest/web/Navigator/deviceMemory.html

**Comment by miquelbeltran** [comment]
Thanks @arnaudruffin this looks good to me now.

I marked the PR as breaking, because it changes a user facing class member type, even if it is just changing from `int` to `double`.

**Review by miquelbeltran — APPROVED** [review]

**Comment by vbuberen** [comment]
I would like to check a few things first. If all is good I will merge and release on Monday.

**Comment by GelistirmeKF** [comment]
Hi, @miquelbeltran @vbuberen, is there a plan for to merge this pull request? It is very urgent for our project.

Thanks,

**Comment by GelistirmeKF** [comment]
Thanks @miquelbeltran for solution alternative. By this package, appreciate the community for valuable efforts 

> @GelistirmeKF This project is run by volunteers and the PR will be merged and released when we have the time to work on it.
> 
> If you are in a hurry, create a fork and import the dependency directly as explained here: https://dart.dev/tools/pub/dependencies#git-packages

**Review by miquelbeltran — CHANGES_REQUESTED** [review]
The `web` version on `device_info_plus` needs to be set to `^1.0.0`, otherwise if Flutter resolves `web 0.5` it won't compile.

I tried to push the commit, but GitHub rejected the push (did you enable allowing maintainers to push changes?)

The required change:

```
diff --git a/packages/device_info_plus/device_info_plus/pubspec.yaml b/packages/device_info_plus/device_info_plus/pubspec.yaml
index 3457c632..0a025afb 100644
--- a/packages/device_info_plus/device_info_plus/pubspec.yaml
+++ b/packages/device_info_plus/device_info_plus/pubspec.yaml
@@ -37,7 +37,7 @@ dependencies:
   flutter_web_plugins:
     sdk: flutter
   meta: ^1.8.0
-  web: ">=0.5.0 <2.0.0"
+  web: ^1.0.0
 
   # win32 is compatible across v4 and v5 for Win32 only (not COM)
   win32: ">=4.0.0 <6.0.0"
```

**Comment by miquelbeltran** [comment]
I managed to push the change to your main branch, git didn't let me at first. Once CI finishes, I will merge this.

I'll do a release for all packages later today.
